move = {"",
"Pound",
"Karate Chop",
"Double Slap",
"Comet Punch",
"Mega Punch",
"Pay Day",
"Fire Punch",
"Ice Punch",
"Thunder Punch",
"Scratch",
"Vise Grip",
"Guillotine",
"Razor Wind",
"Swords Dance",
"Cut",
"Gust",
"Wing Attack",
"Whirlwind",
"Fly",
"Bind",
"Slam",
"Vine Whip",
"Stomp",
"Double Kick",
"Mega Kick",
"Jump Kick",
"Rolling Kick",
"Sand Attack",
"Headbutt",
"Horn Attack",
"Fury Attack",
"Horn Drill",
"Tackle",
"Body Slam",
"Wrap",
"Take Down",
"Thrash",
"Double-Edge",
"Tail Whip",
"Poison Sting",
"Twineedle",
"Pin Missile",
"Leer",
"Bite",
"Growl",
"Roar",
"Sing",
"Supersonic",
"Sonic Boom",
"Disable",
"Acid",
"Ember",
"Flamethrower",
"Mist",
"Water Gun",
"Hydro Pump",
"Surf",
"Ice Beam",
"Blizzard",
"Psybeam",
"Bubble Beam",
"Aurora Beam",
"Hyper Beam",
"Peck",
"Drill Peck",
"Submission",
"Low Kick",
"Counter",
"Seismic Toss",
"Strength",
"Absorb",
"Mega Drain",
"Leech Seed",
"Growth",
"Razor Leaf",
"Solar Beam",
"Poison Powder",
"Stun Spore",
"Sleep Powder",
"Petal Dance",
"String Shot",
"Dragon Rage",
"Fire Spin",
"Thunder Shock",
"Thunderbolt",
"Thunder Wave",
"Thunder",
"Rock Throw",
"Earthquake",
"Fissure",
"Dig",
"Toxic",
"Confusion",
"Psychic",
"Hypnosis",
"Meditate",
"Agility",
"Quick Attack",
"Rage",
"Teleport",
"Night Shade",
"Mimic",
"Screech",
"Double Team",
"Recover",
"Harden",
"Minimize",
"Smokescreen",
"Confuse Ray",
"Withdraw",
"Defense Curl",
"Barrier",
"Light Screen",
"Haze",
"Reflect",
"Focus Energy",
"Bide",
"Metronome",
"Mirror Move",
"Self-Destruct",
"Egg Bomb",
"Lick",
"Smog",
"Sludge",
"Bone Club",
"Fire Blast",
"Waterfall",
"Clamp",
"Swift",
"Skull Bash",
"Spike Cannon",
"Constrict",
"Amnesia",
"Kinesis",
"Soft Boiled",
"High Jump Kick",
"Glare",
"Dream Eater",
"Poison Gas",
"Barrage",
"Leech Life",
"Lovely Kiss",
"Sky Attack",
"Transform",
"Bubble",
"Dizzy Punch",
"Spore",
"Flash",
"Psywave",
"Splash",
"Acid Armor",
"Crabhammer",
"Explosion",
"Fury Swipes",
"Bonemerang",
"Rest",
"Rock Slide",
"Hyper Fang",
"Sharpen",
"Conversion",
"Tri Attack",
"Super Fang",
"Slash",
"Substitute",
"Struggle",
"Sketch",
"Triple Kick",
"Thief",
"Spider Web",
"Mind Reader",
"Nightmare",
"Flame Wheel",
"Snore",
"Curse",
"Flail",
"Conversion 2",
"Aeroblast",
"Cotton Spore",
"Reversal",
"Spite",
"Powder Snow",
"Protect",
"Mach Punch",
"Scary Face",
"Feint Attack",
"Sweet Kiss",
"Belly Drum",
"Sludge Bomb",
"Mud-Slap",
"Octazooka",
"Spikes",
"Zap Cannon",
"Foresight",
"Destiny Bond",
"Perish Song",
"Icy Wind",
"Detect",
"Bone Rush",
"Lock-On",
"Outrage",
"Sandstorm",
"Giga Drain",
"Endure",
"Charm",
"Rollout",
"False Swipe",
"Swagger",
"Milk Drink",
"Spark",
"Fury Cutter",
"Steel Wing",
"Mean Look",
"Attract",
"Sleep Talk",
"Heal Bell",
"Return",
"Present",
"Frustration",
"Safeguard",
"Pain Split",
"Sacred Fire",
"Magnitude",
"Dynamic Punch",
"Megahorn",
"Dragon Breath",
"Baton Pass",
"Encore",
"Pursuit",
"Rapid Spin",
"Sweet Scent",
"Iron Tail",
"Metal Claw",
"Vital Throw",
"Morning Sun",
"Synthesis",
"Moonlight",
"Hidden Power",
"Cross Chop",
"Twister",
"Rain Dance",
"Sunny Day",
"Crunch",
"Mirror Coat",
"Psych Up",
"Extreme Speed",
"Ancient Power",
"Shadow Ball",
"Future Sight",
"Rock Smash",
"Whirlpool",
"Beat Up",
"Fake Out",
"Uproar",
"Stockpile",
"Spit Up",
"Swallow",
"Heat Wave",
"Hail",
"Torment",
"Flatter",
"Will-O-Wisp",
"Memento",
"Facade",
"Focus Punch",
"Smelling Salts",
"Follow Me",
"Nature Power",
"Charge",
"Taunt",
"Helping Hand",
"Trick",
"Role Play",
"Wish",
"Assist",
"Ingrain",
"Superpower",
"Magic Coat",
"Recycle",
"Revenge",
"Brick Break",
"Yawn",
"Knock Off",
"Endeavor",
"Eruption",
"Skill Swap",
"Imprison",
"Refresh",
"Grudge",
"Snatch",
"Secret Power",
"Dive",
"Arm Thrust",
"Camouflage",
"Tail Glow",
"Luster Purge",
"Mist Ball",
"Feather Dance",
"Teeter Dance",
"Blaze Kick",
"Mud Sport",
"Ice Ball",
"Needle Arm",
"Slack Off",
"Hyper Voice",
"Poison Fang",
"Crush Claw",
"Blast Burn",
"Hydro Cannon",
"Meteor Mash",
"Astonish",
"Weather Ball",
"Aromatherapy",
"Fake Tears",
"Air Cutter",
"Overheat",
"Odor Sleuth",
"Rock Tomb",
"Silver Wind",
"Metal Sound",
"Grass Whistle",
"Tickle",
"Cosmic Power",
"Water Spout",
"Signal Beam",
"Shadow Punch",
"Extrasensory",
"Sky Uppercut",
"Sand Tomb",
"Sheer Cold",
"Muddy Water",
"Bullet Seed",
"Aerial Ace",
"Icicle Spear",
"Iron Defense",
"Block",
"Howl",
"Dragon Claw",
"Frenzy Plant",
"Bulk Up",
"Bounce",
"Mud Shot",
"Poison Tail",
"Covet",
"Volt Tackle",
"Magical Leaf",
"Water Sport",
"Calm Mind",
"Leaf Blade",
"Dragon Dance",
"Rock Blast",
"Shock Wave",
"Water Pulse",
"Doom Desire",
"Psycho Boost",
"Roost",
"Gravity",
"Miracle Eye",
"Wake-Up Slap",
"Hammer Arm",
"Gyro Ball",
"Healing Wish",
"Brine",
"Natural Gift",
"Feint",
"Pluck",
"Tailwind",
"Acupressure",
"Metal Burst",
"U-turn",
"Close Combat",
"Payback",
"Assurance",
"Embargo",
"Fling",
"Psycho Shift",
"Trump Card",
"Heal Block",
"Wring Out",
"Power Trick",
"Gastro Acid",
"Lucky Chant",
"Me First",
"Copycat",
"Power Swap",
"Guard Swap",
"Punishment",
"Last Resort",
"Worry Seed",
"Sucker Punch",
"Toxic Spikes",
"Heart Swap",
"Aqua Ring",
"Magnet Rise",
"Flare Blitz",
"Force Palm",
"Aura Sphere",
"Rock Polish",
"Poison Jab",
"Dark Pulse",
"Night Slash",
"Aqua Tail",
"Seed Bomb",
"Air Slash",
"X-Scissor",
"Bug Buzz",
"Dragon Pulse",
"Dragon Rush",
"Power Gem",
"Drain Punch",
"Vacuum Wave",
"Focus Blast",
"Energy Ball",
"Brave Bird",
"Earth Power",
"Switcheroo",
"Giga Impact",
"Nasty Plot",
"Bullet Punch",
"Avalanche",
"Ice Shard",
"Shadow Claw",
"Thunder Fang",
"Ice Fang",
"Fire Fang",
"Shadow Sneak",
"Mud Bomb",
"Psycho Cut",
"Zen Headbutt",
"Mirror Shot",
"Flash Cannon",
"Rock Climb",
"Defog",
"Trick Room",
"Draco Meteor",
"Discharge",
"Lava Plume",
"Leaf Storm",
"Power Whip",
"Rock Wrecker",
"Cross Poison",
"Gunk Shot",
"Iron Head",
"Magnet Bomb",
"Stone Edge",
"Captivate",
"Stealth Rock",
"Grass Knot",
"Chatter",
"Judgment",
"Bug Bite",
"Charge Beam",
"Wood Hammer",
"Aqua Jet",
"Attack Order",
"Defend Order",
"Heal Order",
"Head Smash",
"Double Hit",
"Roar of Time",
"Spacial Rend",
"Lunar Dance",
"Crush Grip",
"Magma Storm",
"Dark Void",
"Seed Flare",
"Ominous Wind",
"Shadow Force",
"Hone Claws",
"Wide Guard",
"Guard Split",
"Power Split",
"Wonder Room",
"Psyshock",
"Venoshock",
"Autotomize",
"Rage Powder",
"Telekinesis",
"Magic Room",
"Smack Down",
"Storm Throw",
"Flame Burst",
"Sludge Wave",
"Quiver Dance",
"Heavy Slam",
"Synchronoise",
"Electro Ball",
"Soak",
"Flame Charge",
"Coil",
"Low Sweep",
"Acid Spray",
"Foul Play",
"Simple Beam",
"Entrainment",
"After You",
"Round",
"Echoed Voice",
"Chip Away",
"Clear Smog",
"Stored Power",
"Quick Guard",
"Ally Switch",
"Scald",
"Shell Smash",
"Heal Pulse",
"Hex",
"Sky Drop",
"Shift Gear",
"Circle Throw",
"Incinerate",
"Quash",
"Acrobatics",
"Reflect Type",
"Retaliate",
"Final Gambit",
"Bestow",
"Inferno",
"Water Pledge",
"Fire Pledge",
"Grass Pledge",
"Volt Switch",
"Struggle Bug",
"Bulldoze",
"Frost Breath",
"Dragon Tail",
"Work Up",
"Electroweb",
"Wild Charge",
"Drill Run",
"Dual Chop",
"Heart Stamp",
"Horn Leech",
"Sacred Sword",
"Razor Shell",
"Heat Crash",
"Leaf Tornado",
"Steamroller",
"Cotton Guard",
"Night Daze",
"Psystrike",
"Tail Slap",
"Hurricane",
"Head Charge",
"Gear Grind",
"Searing Shot",
"Techno Blast",
"Relic Song",
"Secret Sword",
"Glaciate",
"Bolt Strike",
"Blue Flare",
"Fiery Dance",
"Freeze Shock",
"Ice Burn",
"Snarl",
"Icicle Crash",
"V-create",
"Fusion Flare",
"Fusion Bolt",
"Flying Press",
"Mat Block",
"Belch",
"Rototiller",
"Sticky Web",
"Fell Stinger",
"Phantom Force",
"Trick-or-Treat",
"Noble Roar",
"Ion Deluge",
"Parabolic Charge",
"Forest's Curse",
"Petal Blizzard",
"Freeze-Dry",
"Disarming Voice",
"Parting Shot",
"Topsy-Turvy",
"Draining Kiss",
"Crafty Shield",
"Flower Shield",
"Grassy Terrain",
"Misty Terrain",
"Electrify",
"Play Rough",
"Fairy Wind",
"Moonblast",
"Boomburst",
"Fairy Lock",
"King's Shield",
"Play Nice",
"Confide",
"Diamond Storm",
"Steam Eruption",
"Hyperspace Hole",
"Water Shuriken",
"Mystical Fire",
"Spiky Shield",
"Aromatic Mist",
"Eerie Impulse",
"Venom Drench",
"Powder",
"Geomancy",
"Magnetic Flux",
"Happy Hour",
"Electric Terrain",
"Dazzling Gleam",
"Celebrate",
"Hold Hands",
"Baby-Doll Eyes",
"Nuzzle",
"Hold Back",
"Infestation",
"Power-Up Punch",
"Oblivion Wing",
"Thousand Arrows",
"Thousand Waves",
"Land's Wrath",
"Light of Ruin",
"Origin Pulse",
"Precipice Blades",
"Dragon Ascent",
"Hyperspace Fury",
"Shore Up",
"First Impression",
"Baneful Bunker",
"Spirit Shackle",
"Darkest Lariat",
"Sparkling Aria",
"Ice Hammer",
"Floral Healing",
"High Horsepower",
"Strength Sap",
"Solar Blade",
"Leafage",
"Spotlight",
"Toxic Thread",
"Laser Focus",
"Gear Up",
"Throat Chop",
"Pollen Puff",
"Anchor Shot",
"Psychic Terrain",
"Lunge",
"Fire Lash",
"Power Trip",
"Burn Up",
"Speed Swap",
"Smart Strike",
"Purify",
"Revelation Dance",
"Core Enforcer",
"Trop Kick",
"Instruct",
"Beak Blast",
"Clanging Scales",
"Dragon Hammer",
"Brutal Swing",
"Aurora Veil",
"Shell Trap",
"Fleur Cannon",
"Psychic Fangs",
"Stomping Tantrum",
"Shadow Bone",
"Accelerock",
"Liquidation",
"Prismatic Laser",
"Spectral Thief",
"Sunsteel Strike",
"Moongeist Beam",
"Tearful Look",
"Zing Zap",
"Nature's Madness",
"Multi-Attack",
"Mind Blown",
"Plasma Fists",
"Photon Geyser",
"Zippy Zap",
"Splishy Splash",
"Floaty Fall",
"Pika Papow",
"Bouncy Bubble",
"Buzzy Buzz",
"Sizzly Slide",
"Glitzy Glow",
"Baddy Bad",
"Sappy Seed",
"Freezy Frost",
"Sparkly Swirl",
"Veevee Volley",
"Double Iron Bash",
"Dynamax Cannon",
"Snipe Shot",
"Jaw Lock",
"Stuff Cheeks",
"No Retreat",
"Tar Shot",
"Magic Powder",
"Dragon Darts",
"Teatime",
"Octolock",
"Bolt Beak",
"Fishious Rend",
"Court Change",
"Clangorous Soul",
"Body Press",
"Decorate",
"Drum Beating",
"Snap Trap",
"Pyro Ball",
"Behemoth Blade",
"Behemoth Bash",
"Aura Wheel",
"Breaking Swipe",
"Branch Poke",
"Overdrive",
"Apple Acid",
"Grav Apple",
"Spirit Break",
"Strange Steam",
"Life Dew",
"Obstruct",
"False Surrender",
"Meteor Assault",
"Eternabeam",
"Steel Beam",
"Expanding Force",
"Steel Roller",
"Scale Shot",
"Meteor Beam",
"Shell Side Arm",
"Misty Explosion",
"Grassy Glide",
"Rising Voltage",
"Terrain Pulse",
"Skitter Smack",
"Burning Jealousy",
"Lash Out",
"Poltergeist",
"Corrosive Gas",
"Coaching",
"Flip Turn",
"Triple Axel",
"Dual Wingbeat",
"Scorching Sands",
"Jungle Healing",
"Wicked Blow",
"Surging Strikes",
"Thunder Cage",
"Dragon Energy",
"Freezing Glare",
"Fiery Wrath",
"Thunderous Kick",
"Glacial Lance",
"Astral Barrage",
"Eerie Spell",
"Dire Claw",
"Psyshield Bash",
"Power Shift",
"Stone Axe",
"Springtide Storm",
"Mystical Power",
"Raging Fury",
"Wave Crash",
"Chloroblast",
"Mountain Gale",
"Victory Dance",
"Headlong Rush",
"Barb Barrage",
"Esper Wing",
"Bitter Malice",
"Shelter",
"Triple Arrows",
"Infernal Parade",
"Ceaseless Edge",
"Bleakwind Storm",
"Wildbolt Storm",
"Sandsear Storm",
"Lunar Blessing",
"Take Heart",
"Tera Blast",
"Silk Trap",
"Axe Kick",
"Last Respects",
"Lumina Crash",
"Order Up",
"Jet Punch",
"Spicy Extract",
"Spin Out",
"Population Bomb",
"Ice Spinner",
"Glaive Rush",
"Revival Blessing",
"Salt Cure",
"Triple Dive",
"Mortal Spin",
"Doodle",
"Fillet Away",
"Kowtow Cleave",
"Flower Trick",
"Torch Song",
"Aqua Step",
"Raging Bull",
"Make It Rain",
"Ruination",
"Collision Course",
"Electro Drift",
"Shed Tail",
"Chilly Reception",
"Tidy Up",
"Snowscape",
"Pounce",
"Trailblaze",
"Chilling Water",
"Hyper Drill",
"Twin Beam",
"Rage Fist",
"Armor Cannon",
"Bitter Blade",
"Double Shock",
"Gigaton Hammer",
"Comeuppance",
"Aqua Cutter",
"Blazing Torque",
"Wicked Torque",
"Noxious Torque",
"Combat Torque",
"Magical Torque",
"Psyblade",
"Hydro Steam",
"Blood Moon",
"Matcha Gotcha",
"Syrup Bomb",
"Ivy Cudgel",
"Electro Shot",
"Tera Starstorm",
"Fickle Beam",
"Burning Bulwark",
"Thunderclap",
"Mighty Cleave",
"Tachyon Cutter",
"Hard Press",
"Dragon Cheer",
"Alluring Voice",
"Temper Flare",
"Supercell Slam",
"Psychic Noise",
"Upper Hand",
"Malignant Chain"
}

mons = {
"Bulbasaur",
"Ivysaur",
"Venusaur",
"Charmander",
"Charmeleon",
"Charizard",
"Squirtle",
"Wartortle",
"Blastoise",
"Caterpie",
"Metapod",
"Butterfree",
"Weedle",
"Kakuna",
"Beedrill",
"Pidgey",
"Pidgeotto",
"Pidgeot",
"Rattata",
"Raticate",
"Spearow",
"Fearow",
"Ekans",
"Arbok",
"Pikachu",
"Raichu",
"Sandshrew",
"Sandslash",
"Nidoran-F",
"Nidorina",
"Nidoqueen",
"Nidoran-M",
"Nidorino",
"Nidoking",
"Clefairy",
"Clefable",
"Vulpix",
"Ninetales",
"Jigglypuff",
"Wigglytuff",
"Zubat",
"Golbat",
"Oddish",
"Gloom",
"Vileplume",
"Paras",
"Parasect",
"Venonat",
"Venomoth",
"Diglett",
"Dugtrio",
"Meowth",
"Persian",
"Psyduck",
"Golduck",
"Mankey",
"Primeape",
"Growlithe",
"Arcanine",
"Poliwag",
"Poliwhirl",
"Poliwrath",
"Abra",
"Kadabra",
"Alakazam",
"Machop",
"Machoke",
"Machamp",
"Bellsprout",
"Weepinbell",
"Victreebel",
"Tentacool",
"Tentacruel",
"Geodude",
"Graveler",
"Golem",
"Ponyta",
"Rapidash",
"Slowpoke",
"Slowbro",
"Magnemite",
"Magneton",
"Farfetch’d",
"Doduo",
"Dodrio",
"Seel",
"Dewgong",
"Grimer",
"Muk",
"Shellder",
"Cloyster",
"Gastly",
"Haunter",
"Gengar",
"Onix",
"Drowzee",
"Hypno",
"Krabby",
"Kingler",
"Voltorb",
"Electrode",
"Exeggcute",
"Exeggutor",
"Cubone",
"Marowak",
"Hitmonlee",
"Hitmonchan",
"Lickitung",
"Koffing",
"Weezing",
"Rhyhorn",
"Rhydon",
"Chansey",
"Tangela",
"Kangaskhan",
"Horsea",
"Seadra",
"Goldeen",
"Seaking",
"Staryu",
"Starmie",
"Mr. Mime",
"Scyther",
"Jynx",
"Electabuzz",
"Magmar",
"Pinsir",
"Tauros",
"Magikarp",
"Gyarados",
"Lapras",
"Ditto",
"Eevee",
"Vaporeon",
"Jolteon",
"Flareon",
"Porygon",
"Omanyte",
"Omastar",
"Kabuto",
"Kabutops",
"Aerodactyl",
"Snorlax",
"Articuno",
"Zapdos",
"Moltres",
"Dratini",
"Dragonair",
"Dragonite",
"Mewtwo",
"Mew",
"Chikorita",
"Bayleef",
"Meganium",
"Cyndaquil",
"Quilava",
"Typhlosion",
"Totodile",
"Croconaw",
"Feraligatr",
"Sentret",
"Furret",
"Hoothoot",
"Noctowl",
"Ledyba",
"Ledian",
"Spinarak",
"Ariados",
"Crobat",
"Chinchou",
"Lanturn",
"Pichu",
"Cleffa",
"Igglybuff",
"Togepi",
"Togetic",
"Natu",
"Xatu",
"Mareep",
"Flaaffy",
"Ampharos",
"Bellossom",
"Marill",
"Azumarill",
"Sudowoodo",
"Politoed",
"Hoppip",
"Skiploom",
"Jumpluff",
"Aipom",
"Sunkern",
"Sunflora",
"Yanma",
"Wooper",
"Quagsire",
"Espeon",
"Umbreon",
"Murkrow",
"Slowking",
"Misdreavus",
"Unown",
"Wobbuffet",
"Girafarig",
"Pineco",
"Forretress",
"Dunsparce",
"Gligar",
"Steelix",
"Snubbull",
"Granbull",
"Qwilfish",
"Scizor",
"Shuckle",
"Heracross",
"Sneasel",
"Teddiursa",
"Ursaring",
"Slugma",
"Magcargo",
"Swinub",
"Piloswine",
"Corsola",
"Remoraid",
"Octillery",
"Delibird",
"Mantine",
"Skarmory",
"Houndour",
"Houndoom",
"Kingdra",
"Phanpy",
"Donphan",
"Porygon2",
"Stantler",
"Smeargle",
"Tyrogue",
"Hitmontop",
"Smoochum",
"Elekid",
"Magby",
"Miltank",
"Blissey",
"Raikou",
"Entei",
"Suicune",
"Larvitar",
"Pupitar",
"Tyranitar",
"Lugia",
"Ho-Oh",
"Celebi",
"Treecko",
"Grovyle",
"Sceptile",
"Torchic",
"Combusken",
"Blaziken",
"Mudkip",
"Marshtomp",
"Swampert",
"Poochyena",
"Mightyena",
"Zigzagoon",
"Linoone",
"Wurmple",
"Silcoon",
"Beautifly",
"Cascoon",
"Dustox",
"Lotad",
"Lombre",
"Ludicolo",
"Seedot",
"Nuzleaf",
"Shiftry",
"Taillow",
"Swellow",
"Wingull",
"Pelipper",
"Ralts",
"Kirlia",
"Gardevoir",
"Surskit",
"Masquerain",
"Shroomish",
"Breloom",
"Slakoth",
"Vigoroth",
"Slaking",
"Nincada",
"Ninjask",
"Shedinja",
"Whismur",
"Loudred",
"Exploud",
"Makuhita",
"Hariyama",
"Azurill",
"Nosepass",
"Skitty",
"Delcatty",
"Sableye",
"Mawile",
"Aron",
"Lairon",
"Aggron",
"Meditite",
"Medicham",
"Electrike",
"Manectric",
"Plusle",
"Minun",
"Volbeat",
"Illumise",
"Roselia",
"Gulpin",
"Swalot",
"Carvanha",
"Sharpedo",
"Wailmer",
"Wailord",
"Numel",
"Camerupt",
"Torkoal",
"Spoink",
"Grumpig",
"Spinda",
"Trapinch",
"Vibrava",
"Flygon",
"Cacnea",
"Cacturne",
"Swablu",
"Altaria",
"Zangoose",
"Seviper",
"Lunatone",
"Solrock",
"Barboach",
"Whiscash",
"Corphish",
"Crawdaunt",
"Baltoy",
"Claydol",
"Lileep",
"Cradily",
"Anorith",
"Armaldo",
"Feebas",
"Milotic",
"Castform-Normal",
"Kecleon",
"Shuppet",
"Banette",
"Duskull",
"Dusclops",
"Tropius",
"Chimecho",
"Absol",
"Wynaut",
"Snorunt",
"Glalie",
"Spheal",
"Sealeo",
"Walrein",
"Clamperl",
"Huntail",
"Gorebyss",
"Relicanth",
"Luvdisc",
"Bagon",
"Shelgon",
"Salamence",
"Beldum",
"Metang",
"Metagross",
"Regirock",
"Regice",
"Registeel",
"Latias",
"Latios",
"Kyogre",
"Groudon",
"Rayquaza",
"Jirachi",
"Deoxys-Normal",
"Turtwig",
"Grotle",
"Torterra",
"Chimchar",
"Monferno",
"Infernape",
"Piplup",
"Prinplup",
"Empoleon",
"Starly",
"Staravia",
"Staraptor",
"Bidoof",
"Bibarel",
"Kricketot",
"Kricketune",
"Shinx",
"Luxio",
"Luxray",
"Budew",
"Roserade",
"Cranidos",
"Rampardos",
"Shieldon",
"Bastiodon",
"Burmy",
"Wormadam-Plant-Cloak",
"Mothim",
"Combee",
"Vespiquen",
"Pachirisu",
"Buizel",
"Floatzel",
"Cherubi",
"Cherrim",
"Shellos",
"Gastrodon",
"Ambipom",
"Drifloon",
"Drifblim",
"Buneary",
"Lopunny",
"Mismagius",
"Honchkrow",
"Glameow",
"Purugly",
"Chingling",
"Stunky",
"Skuntank",
"Bronzor",
"Bronzong",
"Bonsly",
"Mime Jr.",
"Happiny",
"Chatot",
"Spiritomb",
"Gible",
"Gabite",
"Garchomp",
"Munchlax",
"Riolu",
"Lucario",
"Hippopotas",
"Hippowdon",
"Skorupi",
"Drapion",
"Croagunk",
"Toxicroak",
"Carnivine",
"Finneon",
"Lumineon",
"Mantyke",
"Snover",
"Abomasnow",
"Weavile",
"Magnezone",
"Lickilicky",
"Rhyperior",
"Tangrowth",
"Electivire",
"Magmortar",
"Togekiss",
"Yanmega",
"Leafeon",
"Glaceon",
"Gliscor",
"Mamoswine",
"Porygon-Z",
"Gallade",
"Probopass",
"Dusknoir",
"Froslass",
"Rotom",
"Uxie",
"Mesprit",
"Azelf",
"Dialga",
"Palkia",
"Heatran",
"Regigigas",
"Giratina-Altered",
"Cresselia",
"Phione",
"Manaphy",
"Darkrai",
"Shaymin-Land",
"Arceus-Normal",
"Victini",
"Snivy",
"Servine",
"Serperior",
"Tepig",
"Pignite",
"Emboar",
"Oshawott",
"Dewott",
"Samurott",
"Patrat",
"Watchog",
"Lillipup",
"Herdier",
"Stoutland",
"Purrloin",
"Liepard",
"Pansage",
"Simisage",
"Pansear",
"Simisear",
"Panpour",
"Simipour",
"Munna",
"Musharna",
"Pidove",
"Tranquill",
"Unfezant",
"Blitzle",
"Zebstrika",
"Roggenrola",
"Boldore",
"Gigalith",
"Woobat",
"Swoobat",
"Drilbur",
"Excadrill",
"Audino",
"Timburr",
"Gurdurr",
"Conkeldurr",
"Tympole",
"Palpitoad",
"Seismitoad",
"Throh",
"Sawk",
"Sewaddle",
"Swadloon",
"Leavanny",
"Venipede",
"Whirlipede",
"Scolipede",
"Cottonee",
"Whimsicott",
"Petilil",
"Lilligant",
"Basculin",
"Sandile",
"Krokorok",
"Krookodile",
"Darumaka",
"Darmanitan-Standard-Mode",
"Maractus",
"Dwebble",
"Crustle",
"Scraggy",
"Scrafty",
"Sigilyph",
"Yamask",
"Cofagrigus",
"Tirtouga",
"Carracosta",
"Archen",
"Archeops",
"Trubbish",
"Garbodor",
"Zorua",
"Zoroark",
"Minccino",
"Cinccino",
"Gothita",
"Gothorita",
"Gothitelle",
"Solosis",
"Duosion",
"Reuniclus",
"Ducklett",
"Swanna",
"Vanillite",
"Vanillish",
"Vanilluxe",
"Deerling",
"Sawsbuck",
"Emolga",
"Karrablast",
"Escavalier",
"Foongus",
"Amoonguss",
"Frillish",
"Jellicent",
"Alomomola",
"Joltik",
"Galvantula",
"Ferroseed",
"Ferrothorn",
"Klink",
"Klang",
"Klinklang",
"Tynamo",
"Eelektrik",
"Eelektross",
"Elgyem",
"Beheeyem",
"Litwick",
"Lampent",
"Chandelure",
"Axew",
"Fraxure",
"Haxorus",
"Cubchoo",
"Beartic",
"Cryogonal",
"Shelmet",
"Accelgor",
"Stunfisk",
"Mienfoo",
"Mienshao",
"Druddigon",
"Golett",
"Golurk",
"Pawniard",
"Bisharp",
"Bouffalant",
"Rufflet",
"Braviary",
"Vullaby",
"Mandibuzz",
"Heatmor",
"Durant",
"Deino",
"Zweilous",
"Hydreigon",
"Larvesta",
"Volcarona",
"Cobalion",
"Terrakion",
"Virizion",
"Tornadus",
"Thundurus",
"Reshiram",
"Zekrom",
"Landorus",
"Kyurem",
"Keldeo-Ordinary",
"Meloetta-Aria",
"Genesect",
"Chespin",
"Quilladin",
"Chesnaught",
"Fennekin",
"Braixen",
"Delphox",
"Froakie",
"Frogadier",
"Greninja",
"Bunnelby",
"Diggersby",
"Fletchling",
"Fletchinder",
"Talonflame",
"Scatterbug",
"Spewpa",
"Vivillon",
"Litleo",
"Pyroar",
"Flabebe",
"Floette",
"Florges",
"Skiddo",
"Gogoat",
"Pancham",
"Pangoro",
"Furfrou",
"Espurr",
"Meowstic",
"Honedge",
"Doublade",
"Aegislash-Shield",
"Spritzee",
"Aromatisse",
"Swirlix",
"Slurpuff",
"Inkay",
"Malamar",
"Binacle",
"Barbaracle",
"Skrelp",
"Dragalge",
"Clauncher",
"Clawitzer",
"Helioptile",
"Heliolisk",
"Tyrunt",
"Tyrantrum",
"Amaura",
"Aurorus",
"Sylveon",
"Hawlucha",
"Dedenne",
"Carbink",
"Goomy",
"Sliggoo",
"Goodra",
"Klefki",
"Phantump",
"Trevenant",
"Pumpkaboo-Average",
"Gourgeist-Average",
"Bergmite",
"Avalugg",
"Noibat",
"Noivern",
"Xerneas-Neutral",
"Yveltal",
"Zygarde-50-Aura-Break",
"Diancie",
"Hoopa-Confined",
"Volcanion",
"Rowlet",
"Dartrix",
"Decidueye",
"Litten",
"Torracat",
"Incineroar",
"Popplio",
"Brionne",
"Primarina",
"Pikipek",
"Trumbeak",
"Toucannon",
"Yungoos",
"Gumshoos",
"Grubbin",
"Charjabug",
"Vikavolt",
"Crabrawler",
"Crabominable",
"Oricorio-Baile",
"Cutiefly",
"Ribombee",
"Rockruff",
"Lycanroc",
"Wishiwashi",
"Mareanie",
"Toxapex",
"Mudbray",
"Mudsdale",
"Dewpider",
"Araquanid",
"Fomantis",
"Lurantis",
"Morelull",
"Shiinotic",
"Salandit",
"Salazzle",
"Stufful",
"Bewear",
"Bounsweet",
"Steenee",
"Tsareena",
"Comfey",
"Oranguru",
"Passimian",
"Wimpod",
"Golisopod",
"Sandygast",
"Palossand",
"Pyukumuku",
"Type-Null",
"Silvally-Normal",
"Minior",
"Komala",
"Turtonator",
"Togedemaru",
"Mimikyu-Disguised",
"Bruxish",
"Drampa",
"Dhelmise",
"Jangmo-o",
"Hakamo-o",
"Kommo-o",
"Tapu Koko",
"Tapu Lele",
"Tapu Bulu",
"Tapu Fini",
"Cosmog",
"Cosmoem",
"Solgaleo",
"Lunala",
"Nihilego",
"Buzzwole",
"Pheromosa",
"Xurkitree",
"Celesteela",
"Kartana",
"Guzzlord",
"Necrozma",
"Magearna",
"Marshadow",
"Poipole",
"Naganadel",
"Stakataka",
"Blacephalon",
"Zeraora",
"Meltan",
"Melmetal",
"Grookey",
"Thwackey",
"Rillaboom",
"Scorbunny",
"Raboot",
"Cinderace",
"Sobble",
"Drizzile",
"Inteleon",
"Skwovet",
"Greedent",
"Rookidee",
"Corvisquire",
"Corviknight",
"Blipbug",
"Dottler",
"Orbeetle",
"Nickit",
"Thievul",
"Gossifleur",
"Eldegoss",
"Wooloo",
"Dubwool",
"Chewtle",
"Drednaw",
"Yamper",
"Boltund",
"Rolycoly",
"Carkol",
"Coalossal",
"Applin",
"Flapple",
"Appletun",
"Silicobra",
"Sandaconda",
"Cramorant",
"Arrokuda",
"Barraskewda",
"Toxel",
"Toxtricity",
"Sizzlipede",
"Centiskorch",
"Clobbopus",
"Grapploct",
"Sinistea",
"Polteageist",
"Hatenna",
"Hattrem",
"Hatterene",
"Impidimp",
"Morgrem",
"Grimmsnarl",
"Obstagoon",
"Perrserker",
"Cursola",
"Sirfetch’d",
"Mr. Rime",
"Runerigus",
"Milcery",
"Alcremie-Strawberry-Vanilla-Cream",
"Falinks",
"Pincurchin",
"Snom",
"Frosmoth",
"Stonjourner",
"Eiscue-Ice-Face",
"Indeedee",
"Morpeko",
"Cufant",
"Copperajah",
"Dracozolt",
"Arctozolt",
"Dracovish",
"Arctovish",
"Duraludon",
"Dreepy",
"Drakloak",
"Dragapult",
"Zacian-Hero-Of-Many-Battles",
"Zamazenta-Hero-Of-Many-Battles",
"Eternatus",
"Kubfu",
"Urshifu-Single-Strike-Style",
"Zarude",
"Regieleki",
"Regidrago",
"Glastrier",
"Spectrier",
"Calyrex",
"Wyrdeer",
"Kleavor",
"Ursaluna",
"Basculegion",
"Sneasler",
"Overqwil",
"Enamorus",
"Venusaur-Mega",
"Charizard-Mega-X",
"Charizard-Mega-Y",
"Blastoise-Mega",
"Beedrill-Mega",
"Pidgeot-Mega",
"Alakazam-Mega",
"Slowbro-Mega",
"Gengar-Mega",
"Kangaskhan-Mega",
"Pinsir-Mega",
"Gyarados-Mega",
"Aerodactyl-Mega",
"Mewtwo-Mega-X",
"Mewtwo-Mega-Y",
"Ampharos-Mega",
"Steelix-Mega",
"Scizor-Mega",
"Heracross-Mega",
"Houndoom-Mega",
"Tyranitar-Mega",
"Sceptile-Mega",
"Blaziken-Mega",
"Swampert-Mega",
"Gardevoir-Mega",
"Sableye-Mega",
"Mawile-Mega",
"Aggron-Mega",
"Medicham-Mega",
"Manectric-Mega",
"Sharpedo-Mega",
"Camerupt-Mega",
"Altaria-Mega",
"Banette-Mega",
"Absol-Mega",
"Glalie-Mega",
"Salamence-Mega",
"Metagross-Mega",
"Latias-Mega",
"Latios-Mega",
"Lopunny-Mega",
"Garchomp-Mega",
"Lucario-Mega",
"Abomasnow-Mega",
"Gallade-Mega",
"Audino-Mega",
"Diancie-Mega",
"Rayquaza-Mega",
"Kyogre-Primal",
"Groudon-Primal",
"Rattata-Alola",
"Raticate-Alola",
"Raichu-Alola",
"Sandshrew-Alola",
"Sandslash-Alola",
"Vulpix-Alola",
"Ninetales-Alola",
"Diglett-Alola",
"Dugtrio-Alola",
"Meowth-Alola",
"Persian-Alola",
"Geodude-Alola",
"Graveler-Alola",
"Golem-Alola",
"Grimer-Alola",
"Muk-Alola",
"Exeggutor-Alola",
"Marowak-Alola",
"Meowth-Galar",
"Ponyta-Galar",
"Rapidash-Galar",
"Slowpoke-Galar",
"Slowbro-Galar",
"Farfetch’d-Galar",
"Weezing-Galar",
"Mr. Mime-Galar",
"Articuno-Galar",
"Zapdos-Galar",
"Moltres-Galar",
"Slowking-Galar",
"Corsola-Galar",
"Zigzagoon-Galar",
"Linoone-Galar",
"Darumaka-Galar",
"Darmanitan-Galar-Standard-Mode",
"Yamask-Galar",
"Stunfisk-Galar",
"Growlithe-Hisui",
"Arcanine-Hisui",
"Voltorb-Hisui",
"Electrode-Hisui",
"Typhlosion-Hisui",
"Qwilfish-Hisui",
"Sneasel-Hisui",
"Samurott-Hisui",
"Lilligant-Hisui",
"Zorua-Hisui",
"Zoroark-Hisui",
"Braviary-Hisui",
"Sliggoo-Hisui",
"Goodra-Hisui",
"Avalugg-Hisui",
"Decidueye-Hisui",
"Pikachu-Cosplay",
"Pikachu-Rock-Star",
"Pikachu-Belle",
"Pikachu-Pop-Star",
"Pikachu-Ph-D",
"Pikachu-Libre",
"Pikachu-Original-Cap",
"Pikachu-Hoenn-Cap",
"Pikachu-Sinnoh-Cap",
"Pikachu-Unova-Cap",
"Pikachu-Kalos-Cap",
"Pikachu-Alola-Cap",
"Pikachu-Partner-Cap",
"Pikachu-World-Cap",
"Pichu-Spiky-Eared",
"Unown-B",
"Unown-C",
"Unown-D",
"Unown-E",
"Unown-F",
"Unown-G",
"Unown-H",
"Unown-I",
"Unown-J",
"Unown-K",
"Unown-L",
"Unown-M",
"Unown-N",
"Unown-O",
"Unown-P",
"Unown-Q",
"Unown-R",
"Unown-S",
"Unown-T",
"Unown-U",
"Unown-V",
"Unown-W",
"Unown-X",
"Unown-Y",
"Unown-Z",
"Unown-Emark",
"Unown-Qmark",
"Castform-Sunny",
"Castform-Rainy",
"Castform-Snowy",
"Deoxys-Attack",
"Deoxys-Defense",
"Deoxys-Speed",
"Burmy",
"Burmy",
"Wormadam-Sandy-Cloak",
"Wormadam-Trash-Cloak",
"Cherrim-Sunshine",
"Shellos",
"Gastrodon",
"Rotom-Heat",
"Rotom-Wash",
"Rotom-Frost",
"Rotom-Fan",
"Rotom-Mow",
"Dialga-Origin",
"Palkia-Origin",
"Giratina-Origin",
"Shaymin-Sky",
"Arceus-Fighting",
"Arceus-Flying",
"Arceus-Poison",
"Arceus-Ground",
"Arceus-Rock",
"Arceus-Bug",
"Arceus-Ghost",
"Arceus-Steel",
"Arceus-Fire",
"Arceus-Water",
"Arceus-Grass",
"Arceus-Electric",
"Arceus-Psychic",
"Arceus-Ice",
"Arceus-Dragon",
"Arceus-Dark",
"Arceus-Fairy",
"Basculin-Blue-Striped",
"Basculin-White-Striped",
"Darmanitan-Zen-Mode",
"Darmanitan-Galar-Zen-Mode",
"Deerling-Summer",
"Deerling-Autumn",
"Deerling-Winter",
"Sawsbuck-Summer",
"Sawsbuck-Autumn",
"Sawsbuck-Winter",
"Tornadus-Therian",
"Thundurus-Therian",
"Landorus-Therian",
"Enamorus-Therian",
"Kyurem-White",
"Kyurem-Black",
"Keldeo-Resolute",
"Meloetta-Pirouette",
"Genesect-Douse-Drive",
"Genesect-Shock-Drive",
"Genesect-Burn-Drive",
"Genesect-Chill-Drive",
"Greninja-Battle-Bond",
"Greninja-Ash",
"Vivillon",
"Vivillon",
"Vivillon",
"Vivillon",
"Vivillon",
"Vivillon",
"Vivillon",
"Vivillon",
"Vivillon",
"Vivillon",
"Vivillon",
"Vivillon",
"Vivillon",
"Vivillon",
"Vivillon",
"Vivillon",
"Vivillon",
"Vivillon",
"Vivillon",
"Flabebe-Yellow-Flower",
"Flabebe-Orange-Flower",
"Flabebe-Blue-Flower",
"Flabebe-White-Flower",
"Floette-Yellow-Flower",
"Floette-Orange-Flower",
"Floette-Blue-Flower",
"Floette-White-Flower",
"Floette-Eternal-Flower",
"Florges-Yellow-Flower",
"Florges-Orange-Flower",
"Florges-Blue-Flower",
"Florges-White-Flower",
"Furfrou-Heart-Trim",
"Furfrou-Star-Trim",
"Furfrou-Diamond-Trim",
"Furfrou-Debutante-Trim",
"Furfrou-Matron-Trim",
"Furfrou-Dandy-Trim",
"Furfrou-La-Reine-Trim",
"Furfrou-Kabuki-Trim",
"Furfrou-Pharaoh-Trim",
"Meowstic-F",
"Aegislash-Blade",
"Pumpkaboo-Small",
"Pumpkaboo-Large",
"Pumpkaboo-Super",
"Gourgeist-Small",
"Gourgeist-Large",
"Gourgeist-Super",
"Xerneas-Active",
"Zygarde-10-Aura-Break",
"Zygarde-10-Power-Construct",
"Zygarde-50-Power-Construct",
"Zygarde-Complete",
"Hoopa-Unbound",
"Oricorio-Pom-Pom",
"Oricorio-Pau",
"Oricorio-Sensu",
"Rockruff-Own-Tempo",
"Lycanroc-Midnight",
"Lycanroc-Dusk",
"Wishiwashi-School",
"Silvally-Fighting",
"Silvally-Flying",
"Silvally-Poison",
"Silvally-Ground",
"Silvally-Rock",
"Silvally-Bug",
"Silvally-Ghost",
"Silvally-Steel",
"Silvally-Fire",
"Silvally-Water",
"Silvally-Grass",
"Silvally-Electric",
"Silvally-Psychic",
"Silvally-Ice",
"Silvally-Dragon",
"Silvally-Dark",
"Silvally-Fairy",
"Minior",
"Minior",
"Minior",
"Minior",
"Minior",
"Minior",
"Minior",
"Minior",
"Minior",
"Minior",
"Minior",
"Minior",
"Minior",
"Mimikyu-Busted",
"Necrozma-Dusk-Mane",
"Necrozma-Dawn-Wings",
"Necrozma-Ultra",
"Magearna-Original-Color",
"Cramorant-Gulping",
"Cramorant-Gorging",
"Toxtricity",
"Sinistea-Antique",
"Polteageist-Antique",
"Alcremie-Strawberry-Ruby-Cream",
"Alcremie-Strawberry-Matcha-Cream",
"Alcremie-Strawberry-Mint-Cream",
"Alcremie-Strawberry-Lemon-Cream",
"Alcremie-Strawberry-Salted-Cream",
"Alcremie-Strawberry-Ruby-Swirl",
"Alcremie-Strawberry-Caramel-Swirl",
"Alcremie-Strawberry-Rainbow-Swirl",
"Eiscue-Noice-Face",
"Indeedee-F",
"Morpeko-Hangry",
"Zacian-Crowned-Sword",
"Zamazenta-Crowned-Shield",
"Eternatus-Eternamax",
"Urshifu-Rapid-Strike-Style",
"Zarude-Dada",
"Calyrex-Ice-Rider",
"Calyrex-Shadow-Rider",
"Basculegion-F",
"Alcremie-Berry-Vanilla-Cream",
"Alcremie-Berry-Ruby-Cream",
"Alcremie-Berry-Matcha-Cream",
"Alcremie-Berry-Mint-Cream",
"Alcremie-Berry-Lemon-Cream",
"Alcremie-Berry-Salted-Cream",
"Alcremie-Berry-Ruby-Swirl",
"Alcremie-Berry-Caramel-Swirl",
"Alcremie-Berry-Rainbow-Swirl",
"Alcremie-Love-Vanilla-Cream",
"Alcremie-Love-Ruby-Cream",
"Alcremie-Love-Matcha-Cream",
"Alcremie-Love-Mint-Cream",
"Alcremie-Love-Lemon-Cream",
"Alcremie-Love-Salted-Cream",
"Alcremie-Love-Ruby-Swirl",
"Alcremie-Love-Caramel-Swirl",
"Alcremie-Love-Rainbow-Swirl",
"Alcremie-Star-Vanilla-Cream",
"Alcremie-Star-Ruby-Cream",
"Alcremie-Star-Matcha-Cream",
"Alcremie-Star-Mint-Cream",
"Alcremie-Star-Lemon-Cream",
"Alcremie-Star-Salted-Cream",
"Alcremie-Star-Ruby-Swirl",
"Alcremie-Star-Caramel-Swirl",
"Alcremie-Star-Rainbow-Swirl",
"Alcremie-Clover-Vanilla-Cream",
"Alcremie-Clover-Ruby-Cream",
"Alcremie-Clover-Matcha-Cream",
"Alcremie-Clover-Mint-Cream",
"Alcremie-Clover-Lemon-Cream",
"Alcremie-Clover-Salted-Cream",
"Alcremie-Clover-Ruby-Swirl",
"Alcremie-Clover-Caramel-Swirl",
"Alcremie-Clover-Rainbow-Swirl",
"Alcremie-Flower-Vanilla-Cream",
"Alcremie-Flower-Ruby-Cream",
"Alcremie-Flower-Matcha-Cream",
"Alcremie-Flower-Mint-Cream",
"Alcremie-Flower-Lemon-Cream",
"Alcremie-Flower-Salted-Cream",
"Alcremie-Flower-Ruby-Swirl",
"Alcremie-Flower-Caramel-Swirl",
"Alcremie-Flower-Rainbow-Swirl",
"Alcremie-Ribbon-Vanilla-Cream",
"Alcremie-Ribbon-Ruby-Cream",
"Alcremie-Ribbon-Matcha-Cream",
"Alcremie-Ribbon-Mint-Cream",
"Alcremie-Ribbon-Lemon-Cream",
"Alcremie-Ribbon-Salted-Cream",
"Alcremie-Ribbon-Ruby-Swirl",
"Alcremie-Ribbon-Caramel-Swirl",
"Alcremie-Ribbon-Rainbow-Swirl",
"Sprigatito",
"Floragato",
"Meowscarada",
"Fuecoco",
"Crocalor",
"Skeledirge",
"Quaxly",
"Quaxwell",
"Quaquaval",
"Lechonk",
"Oinkologne",
"Oinkologne-F",
"Tarountula",
"Spidops",
"Nymble",
"Lokix",
"Pawmi",
"Pawmo",
"Pawmot",
"Tandemaus",
"Maushold",
"Maushold",
"Fidough",
"Dachsbun",
"Smoliv",
"Dolliv",
"Arboliva",
"Squawkabilly",
"Squawkabilly",
"Squawkabilly",
"Squawkabilly",
"Nacli",
"Naclstack",
"Garganacl",
"Charcadet",
"Armarouge",
"Ceruledge",
"Tadbulb",
"Bellibolt",
"Wattrel",
"Kilowattrel",
"Maschiff",
"Mabosstiff",
"Shroodle",
"Grafaiai",
"Bramblin",
"Brambleghast",
"Toedscool",
"Toedscruel",
"Klawf",
"Capsakid",
"Scovillain",
"Rellor",
"Rabsca",
"Flittle",
"Espathra",
"Tinkatink",
"Tinkatuff",
"Tinkaton",
"Wiglett",
"Wugtrio",
"Bombirdier",
"Finizen",
"Palafin-Zero",
"Palafin-Hero",
"Varoom",
"Revavroom",
"Cyclizar",
"Orthworm",
"Glimmet",
"Glimmora",
"Greavard",
"Houndstone",
"Flamigo",
"Cetoddle",
"Cetitan",
"Veluza",
"Dondozo",
"Tatsugiri",
"Tatsugiri",
"Tatsugiri",
"Annihilape",
"Clodsire",
"Farigiraf",
"Dudunsparce",
"Dudunsparce",
"Kingambit",
"Great Tusk",
"Scream Tail",
"Brute Bonnet",
"Flutter Mane",
"Slither Wing",
"Sandy Shocks",
"Iron Treads",
"Iron Bundle",
"Iron Hands",
"Iron Jugulis",
"Iron Moth",
"Iron Thorns",
"Frigibax",
"Arctibax",
"Baxcalibur",
"Gimmighoul-Chest",
"Gimmighoul-Roaming",
"Gholdengo",
"Wo-Chien",
"Chien-Pao",
"Ting-Lu",
"Chi-Yu",
"Roaring Moon",
"Iron Valiant",
"Koraidon",
"Miraidon",
"Tauros-Paldea-Combat",
"Tauros-Paldea-Blaze",
"Tauros-Paldea-Aqua",
"Wooper-Paldea",
"Walking Wake",
"Iron Leaves",
"Dipplin",
"Poltchageist",
"Poltchageist",
"Sinistcha",
"Sinistcha",
"Okidogi",
"Munkidori",
"Fezandipiti",
"Ogerpon",
"Ogerpon-Wellspring",
"Ogerpon-Hearthflame",
"Ogerpon-Cornerstone",
"Ogerpon-Teal-Mask-Tera",
"Ogerpon-Wellspring-Mask-Tera",
"Ogerpon-Hearthflame-Mask-Tera",
"Ogerpon-Cornerstone-Mask-Tera",
"Ursaluna-Bloodmoon",
"Archaludon",
"Hydrapple",
"Gouging Fire",
"Raging Bolt",
"Iron Boulder",
"Iron Crown",
"Terapagos-Normal",
"Terapagos-Terastal",
"Terapagos-Stellar",
"Pecharunt"
}

ability = {'None','None','None',
'Overgrow','Chlorophyll','None',
'Overgrow','Chlorophyll','None',
'Overgrow','Chlorophyll','None',
'Blaze','Solar Power','None',
'Blaze','Solar Power','None',
'Blaze','Solar Power','None',
'Torrent','Rain Dish','None',
'Torrent','Rain Dish','None',
'Torrent','Rain Dish','None',
'Shield Dust','None','Run Away',
'Shed Skin','None','None',
'Compound Eyes','None','Tinted Lens',
'Shield Dust','None','Run Away',
'Shed Skin','None','None',
'Swarm','None','Sniper',
'Big Pecks','None','Tangled Feet',
'Big Pecks','None','Tangled Feet',
'Big Pecks','None','Tangled Feet',
'Guts','None','Hustle',
'Guts','None','Hustle',
'Sniper','None','None',
'Sniper','None','None',
'Intimidate','None','Unnerve',
'Intimidate','None','Unnerve',
'Static','None','Lightning Rod',
'Static','None','Lightning Rod',
'Sand Rush','None','Sand Veil',
'Sand Rush','None','Sand Veil',
'Poison Point','None','Hustle',
'Poison Point','None','Hustle',
'Poison Point','None','Sheer Force',
'Poison Point','None','Hustle',
'Poison Point','None','Hustle',
'Poison Point','None','Sheer Force',
'Friend Guard','Magic Guard','Cute Charm',
'Unaware','Magic Guard','Cute Charm',
'Mystic Charm','None','Drought',
'Mystic Charm','None','Drought',
'Friend Guard','None','Competitive',
'Friend Guard','None','Competitive',
'Inner Focus','Infiltrator','None',
'Inner Focus','Infiltrator','None',
'Chlorophyll','None','Run Away',
'Chlorophyll','None','Stench',
'Chlorophyll','None','Effect Spore',
'Hyper Cutter','None','Effect Spore',
'Hyper Cutter','None','Effect Spore',
'Compound Eyes','Tinted Lens','Run Away',
'Shield Dust','Tinted Lens','Wonder Skin',
'Arena Trap','None','Sand Force',
'Arena Trap','None','Sand Force',
'Technician','None','Unnerve',
'Technician','None','Unnerve',
'Swift Swim','Cloud Nine','Damp',
'Swift Swim','Cloud Nine','Damp',
'Vital Spirit','None','Defiant',
'Vital Spirit','None','Defiant',
'Intimidate','None','Flash Fire',
'Intimidate','None','Justified',
'Swift Swim','None','Water Absorb',
'Swift Swim','None','Water Absorb',
'Swift Swim','None','Water Absorb',
'Synchronize','Inner Focus','Magic Guard',
'Synchronize','Inner Focus','Magic Guard',
'Synchronize','Inner Focus','Magic Guard',
'Guts','No Guard','Steadfast',
'Guts','No Guard','Steadfast',
'Guts','No Guard','Steadfast',
'Chlorophyll','None','Gluttony',
'Chlorophyll','None','Gluttony',
'Chlorophyll','None','Gluttony',
'Clear Body','Liquid Ooze','Rain Dish',
'Clear Body','Liquid Ooze','Rain Dish',
'Rock Head','Sturdy','Sand Veil',
'Rock Head','Sturdy','Sand Veil',
'Rock Head','Sturdy','Sand Veil',
'Reckless','None','Flame Body',
'Reckless','None','Flame Body',
'Own Tempo','None','Regenerator',
'Own Tempo','None','Regenerator',
'Magnet Pull','Analytic','Sturdy',
'Magnet Pull','Analytic','Sturdy',
'Inner Focus','None','Defiant',
'Keen Eye','None','Tangled Feet',
'Keen Eye','None','Tangled Feet',
'Thick Fat','Hydration','Ice Body',
'Thick Fat','Hydration','Ice Body',
'Sticky Hold','Poison Touch','Stench',
'Sticky Hold','Poison Touch','Stench',
'Shell Armor','Skill Link','Overcoat',
'Shell Armor','Skill Link','Overcoat',
'Levitate','None','None',
'Levitate','None','None',
'Cursed Body','None','Levitate',
'Rock Head','Weak Armor','Sturdy',
'Insomnia','Inner Focus','Bad Dreams',
'Insomnia','Inner Focus','Bad Dreams',
'Sheer Force','Shell Armor','Hyper Cutter',
'Sheer Force','Shell Armor','Hyper Cutter',
'Soundproof','Static','Galvanize',
'Soundproof','Static','Galvanize',
'Chlorophyll','None','Harvest',
'Chlorophyll','None','Harvest',
'Battle Armor','None','Lightning Rod',
'Battle Armor','None','Lightning Rod',
'Striker','None','Unburden',
'Iron Fist','None','Inner Focus',
'Cloud Nine','None','Oblivious',
'Levitate','None','Stench',
'Levitate','None','Neutralizing Gas',
'Reckless','Rock Head','Lightning Rod',
'Reckless','Rock Head','Lightning Rod',
'Natural Cure','Healer','Serene Grace',
'Chlorophyll','Leaf Guard','Regenerator',
'Inner Focus','Scrappy','Inner Focus',
'Swift Swim','Sniper','Damp',
'Poison Point','Sniper','Damp',
'Swift Swim','None','Lightning Rod',
'Swift Swim','None','Lightning Rod',
'Illuminate','Natural Cure','Analytic',
'Illuminate','Natural Cure','Analytic',
'Soundproof','Filter','Technician',
'Swarm','Technician','Steadfast',
'Hydration','None','Dry Skin',
'Vital Spirit','None','Static',
'Vital Spirit','None','Flame Body',
'Hyper Cutter','Mold Breaker','Moxie',
'Intimidate','Intimidate','Sheer Force',
'Swift Swim','Swift Swim','Rattled',
'Intimidate','Intimidate','Moxie',
'Shell Armor','Shell Armor','Water Absorb',
'Limber','Limber','Imposter',
'Adaptability','None','Run Away',
'Hydration','None','Water Absorb',
'Quick Feet','None','Volt Absorb',
'Guts','None','Flash Fire',
'Trace','Analytic','Download',
'Swift Swim','Shell Armor','Weak Armor',
'Swift Swim','Shell Armor','Weak Armor',
'Swift Swim','Battle Armor','Weak Armor',
'Swift Swim','Battle Armor','Weak Armor',
'Rock Head','Unnerve','Pressure',
'Gluttony','Thick Fat','Immunity',
'Snow Cloak','None','Pressure',
'Static','None','Pressure',
'Flame Body','None','Pressure',
'Shed Skin','None','Marvel Scale',
'Shed Skin','None','Marvel Scale',
'Inner Focus','None','Multiscale',
'Pressure','None','Unnerve',
'Synchronize','None','None',
'Overgrow','None','Leaf Guard',
'Overgrow','None','Leaf Guard',
'Overgrow','None','Leaf Guard',
'Blaze','None','Flash Fire',
'Blaze','None','Flash Fire',
'Blaze','None','Flash Fire',
'Sheer Force','None','Torrent',
'Sheer Force','None','Torrent',
'Sheer Force','None','Torrent',
'Run Away','None','Adaptability',
'Run Away','None','Adaptability',
'Insomnia','Tinted Lens','Keen Eye',
'Insomnia','Tinted Lens','Keen Eye',
'Rattled','None','Early Bird',
'Rattled','None','Iron Fist',
'Insomnia','Sniper','Swarm',
'Insomnia','Sniper','Swarm',
'Inner Focus','Infiltrator','None',
'Volt Absorb','None','Water Absorb',
'Volt Absorb','None','Water Absorb',
'Static','None','Lightning Rod',
'Friend Guard','Magic Guard','Cute Charm',
'Friend Guard','None','Competitive',
'Super Luck','Serene Grace','Hustle',
'Super Luck','Serene Grace','Hustle',
'Synchronize','None','Magic Bounce',
'Synchronize','None','Magic Bounce',
'Static','Plus','None',
'Static','Plus','None',
'Static','Plus','None',
'Chlorophyll','None','Healer',
'Huge Power','None','Sap Sipper',
'Huge Power','None','Sap Sipper',
'Sturdy','Rock Head','Rock Head',
'Hydration','None','Drizzle',
'Chlorophyll','Infiltrator','Leaf Guard',
'Chlorophyll','Infiltrator','Leaf Guard',
'Chlorophyll','Infiltrator','Cotton Down',
'Run Away','None','Skill Link',
'Chlorophyll','Solar Power','Early Bird',
'Chlorophyll','Solar Power','Flower Veil',
'Compound Eyes','None','Speed Boost',
'Unaware','None','Water Absorb',
'Unaware','None','Water Absorb',
'Synchronize','None','Magic Bounce',
'Synchronize','None','Inner Focus',
'Insomnia','Super Luck','Prankster',
'Own Tempo','None','Regenerator',
'Levitate','None','None',
'Levitate','None','None',
'Shadow Tag','None','Telepathy',
'Inner Focus','None','Sap Sipper',
'Overcoat','None','Sturdy',
'Overcoat','None','Sturdy',
'Rattled','None','Serene Grace',
'Hyper Cutter','None','Immunity',
'Rock Head','Sheer Force','Sturdy',
'Intimidate','Run Away','Rattled',
'Intimidate','Quick Feet','Rattled',
'Intimidate','Swift Swim','Poison Point',
'Swarm','None','Technician',
'Sturdy','Gluttony','Contrary',
'Swarm','Guts','Moxie',
'Inner Focus','None','Pickpocket',
'Quick Feet','Quick Feet','Honey Gather',
'Guts','Quick Feet','Unnerve',
'Magma Armor','Flame Body','Weak Armor',
'Magma Armor','Flame Body','Weak Armor',
'Oblivious','Thick Fat','Snow Cloak',
'Oblivious','Thick Fat','Snow Cloak',
'Regenerator','Natural Cure','Hustle',
'Hustle','Sniper','Moody',
'Suction Cups','Sniper','Moody',
'Vital Spirit','None','Hustle',
'Swift Swim','Water Veil','Water Absorb',
'Keen Eye','None','Sturdy',
'Unnerve','None','Flash Fire',
'Unnerve','None','Flash Fire',
'Swift Swim','Sniper','Damp',
'Cute Charm','None','Sand Veil',
'Sturdy','None','Sand Veil',
'Trace','Analytic','Download',
'Intimidate','None','Sap Sipper',
'Own Tempo','Technician','Moody',
'Guts','None','Vital Spirit',
'Technician','None','Intimidate',
'Oblivious','None','Hydration',
'Vital Spirit','None','Static',
'Vital Spirit','None','Flame Body',
'Thick Fat','Scrappy','Sap Sipper',
'Natural Cure','Serene Grace','Healer',
'Pressure','None','Inner Focus',
'Pressure','None','Inner Focus',
'Pressure','None','Inner Focus',
'Guts','None','Sand Veil',
'Shed Skin','None','None',
'Unnerve','None','Sand Stream',
'Pressure','None','Multiscale',
'Pressure','None','Regenerator',
'Natural Cure','None','None',
'Overgrow','None','Unburden',
'Overgrow','None','Unburden',
'Overgrow','None','Unburden',
'Blaze','None','Speed Boost',
'Blaze','None','Speed Boost',
'Blaze','None','Speed Boost',
'Torrent','None','Damp',
'Torrent','None','Damp',
'Torrent','None','Damp',
'Run Away','Quick Feet','Rattled',
'Intimidate','Quick Feet','Moxie',
'Quick Feet','None','Gluttony',
'Quick Feet','None','Gluttony',
'Shield Dust','None','Run Away',
'Shed Skin','None','None',
'Swarm','None','Rivalry',
'Shed Skin','None','None',
'Shield Dust','None','Compound Eyes',
'Swift Swim','Rain Dish','Own Tempo',
'Swift Swim','Rain Dish','Own Tempo',
'Swift Swim','Rain Dish','Own Tempo',
'Chlorophyll','None','Pickpocket',
'Chlorophyll','None','Pickpocket',
'Chlorophyll','None','Wind Rider',
'Guts','None','Scrappy',
'Guts','None','Scrappy',
'Rain Dish','None','Hydration',
'Rain Dish','None','Drizzle',
'Synchronize','Trace','Telepathy',
'Synchronize','Trace','Telepathy',
'Synchronize','Trace','Telepathy',
'Swift Swim','None','Rain Dish',
'Intimidate','None','Unnerve',
'Quick Feet','Poison Heal','Effect Spore',
'Technician','Poison Heal','Effect Spore',
'Truant','None','None',
'Vital Spirit','None','None',
'Truant','None','None',
'Compound Eyes','None','Run Away',
'Infiltrator','None','Speed Boost',
'Wonder Guard','None','None',
'Soundproof','Rattled','Punk Rock',
'Soundproof','Scrappy','Punk Rock',
'Soundproof','Scrappy','Punk Rock',
'Thick Fat','Guts','Sheer Force',
'Thick Fat','Guts','Sheer Force',
'Thick Fat','None','Huge Power',
'Sturdy','Magnet Pull','Sand Force',
'Normalize','None','None',
'Normalize','None','None',
'Prankster','Prankster','Prankster',
'Hyper Cutter','Intimidate','Sheer Force',
'Heavy Metal','Rock Head','Sturdy',
'Heavy Metal','Rock Head','Sturdy',
'Heavy Metal','Rock Head','Sturdy',
'Pure Power','None','Telepathy',
'Pure Power','None','Telepathy',
'Static','Minus','Lightning Rod',
'Static','Minus','Lightning Rod',
'Plus','None','Lightning Rod',
'Minus','None','Volt Absorb',
'Prankster','None','Swarm',
'Tinted Lens','None','Prankster',
'Natural Cure','Poison Point','Leaf Guard',
'Liquid Ooze','Sticky Hold','Gluttony',
'Liquid Ooze','Sticky Hold','Gluttony',
'Rough Skin','None','Speed Boost',
'Rough Skin','None','Speed Boost',
'Multiscale','None','Oblivious',
'Multiscale','None','Oblivious',
'Oblivious','None','Simple',
'Magma Armor','None','Anger Point',
'Shell Armor','None','Drought',
'Thick Fat','None','Gluttony',
'Thick Fat','None','Gluttony',
'Own Tempo','None','Contrary',
'Arena Trap','Hyper Cutter','Sheer Force',
'Levitate','None','None',
'Levitate','None','None',
'Sand Rush','None','Sand Veil',
'Sand Rush','None','Sand Veil',
'Natural Cure','None','Cloud Nine',
'Natural Cure','None','Cloud Nine',
'Toxic Boost','None','None',
'Fatal Precision','None','Infiltrator',
'Levitate','None','None',
'Levitate','None','None',
'Oblivious','Hydration','Adaptability',
'Oblivious','Hydration','Adaptability',
'Adaptability','Shell Armor','Hyper Cutter',
'Adaptability','Shell Armor','Hyper Cutter',
'Levitate','None','None',
'Levitate','None','None',
'Suction Cups','None','Storm Drain',
'Suction Cups','None','Storm Drain',
'Battle Armor','None','Swift Swim',
'Battle Armor','None','Swift Swim',
'Swift Swim','None','None',
'Marvel Scale','None','Competitive',
'Forecast','None','None',
'Protean','None','Color Change',
'Insomnia','None','Cursed Body',
'Insomnia','None','Cursed Body',
'Levitate','None','Frisk',
'Cursed Body','None','Pressure',
'Chlorophyll','Harvest','Solar Power',
'Levitate','None','None',
'Super Luck','None','Justified',
'Shadow Tag','None','Telepathy',
'Inner Focus','None','Moody',
'Inner Focus','None','Moody',
'Thick Fat','Ice Body','Oblivious',
'Thick Fat','Ice Body','Oblivious',
'Thick Fat','Ice Body','Oblivious',
'Shell Armor','None','Rattled',
'Swift Swim','None','Water Veil',
'Swift Swim','None','Hydration',
'Swift Swim','Rock Head','Sturdy',
'Run Away','None','Swift Swim',
'Rock Head','None','Sheer Force',
'Rock Head','None','Overcoat',
'Intimidate','None','Moxie',
'Clear Body','None','Light Metal',
'Clear Body','None','Light Metal',
'Clear Body','None','Light Metal',
'Clear Body','None','Sturdy',
'Clear Body','None','Ice Body',
'Clear Body','None','Light Metal',
'Levitate','None','None',
'Levitate','None','None',
'Drizzle','None','None',
'Drought','None','None',
'Air Lock','None','None',
'Serene Grace','None','None',
'Synchronize','None','Pressure',
'Shell Armor','None','Overgrow',
'Shell Armor','None','Overgrow',
'Shell Armor','None','Overgrow',
'Blaze','Iron Fist','None',
'Blaze','Iron Fist','None',
'Blaze','Iron Fist','None',
'Torrent','None','Competitive',
'Torrent','None','Competitive',
'Torrent','None','Competitive',
'Keen Eye','None','Reckless',
'Intimidate','None','Reckless',
'Intimidate','None','Reckless',
'Unaware','None','Simple',
'Unaware','None','Simple',
'Shed Skin','None','None',
'Technician','None','None',
'Guts','Intimidate','None',
'Guts','Intimidate','None',
'Guts','Intimidate','None',
'Natural Cure','Poison Point','Leaf Guard',
'Natural Cure','Technician','Leaf Guard',
'Mold Breaker','Sheer Force','None',
'Mold Breaker','Sheer Force','None',
'Sturdy','Soundproof','None',
'Sturdy','Soundproof','None',
'Overcoat','None','None',
'Overcoat','None','None',
'Swarm','None','None',
'Hustle','None','Honey Gather',
'Unnerve','None','Queenly Majesty',
'Run Away','None','Volt Absorb',
'Swift Swim','Water Veil','Technician',
'Swift Swim','Water Veil','Technician',
'Chlorophyll','None','None',
'Flower Gift','None','None',
'Sticky Hold','Sand Force','Storm Drain',
'Sticky Hold','Sand Force','Storm Drain',
'Technician','None','Skill Link',
'Flare Boost','Unburden','Aftermath',
'Flare Boost','Unburden','Aftermath',
'Limber','None','Cute Charm',
'Limber','None','Cute Charm',
'Levitate','None','None',
'Insomnia','Super Luck','Moxie',
'Limber','None','Own Tempo',
'Thick Fat','None','Defiant',
'Levitate','None','None',
'Keen Eye','Aftermath','Stench',
'Keen Eye','Aftermath','Stench',
'Levitate','Heatproof','Heavy Metal',
'Levitate','Heatproof','Heavy Metal',
'Sturdy','Rock Head','Rattled',
'Soundproof','Filter','Technician',
'Natural Cure','Friend Guard','Serene Grace',
'Punk Rock','None','Tangled Feet',
'Infiltrator','None','Pressure',
'Rough Skin','None','Sand Veil',
'Rough Skin','None','Sand Veil',
'Rough Skin','None','Sand Veil',
'Gluttony','Thick Fat','Pickup',
'Inner Focus','None','Prankster',
'Inner Focus','None','Justified',
'Sand Force','None','Sand Stream',
'Sand Force','None','Sand Stream',
'Battle Armor','None','Sniper',
'Battle Armor','None','Sniper',
'Poison Touch','None','Dry Skin',
'Poison Touch','None','Dry Skin',
'Levitate','None','None',
'Swift Swim','Water Veil','Storm Drain',
'Swift Swim','Water Veil','Storm Drain',
'Swift Swim','Water Veil','Water Absorb',
'Soundproof','None','Snow Warning',
'Soundproof','None','Snow Warning',
'Inner Focus','None','Pickpocket',
'Magnet Pull','Analytic','Sturdy',
'Cloud Nine','None','Own Tempo',
'Solid Rock','None','Lightning Rod',
'Chlorophyll','Leaf Guard','Regenerator',
'Vital Spirit','None','Motor Drive',
'Vital Spirit','None','Flame Body',
'Super Luck','Serene Grace','Super Luck',
'Tinted Lens','None','Speed Boost',
'Chlorophyll','None','Leaf Guard',
'Slush Rush','None','Snow Cloak',
'Hyper Cutter','None','Poison Heal',
'Oblivious','Thick Fat','Snow Cloak',
'Adaptability','None','Download',
'Sharpness','None','Justified',
'Sand Force','Magnet Pull','Sturdy',
'Intimidate','None','Pressure',
'Cursed Body','None','Snow Cloak',
'Levitate','None','None',
'Levitate','None','None',
'Levitate','None','None',
'Levitate','None','None',
'Pressure','None','Telepathy',
'Pressure','None','Telepathy',
'Flame Body','None','Flash Fire',
'Slow Start','None','None',
'Pressure','None','Telepathy',
'Levitate','None','None',
'Hydration','None','None',
'Hydration','None','None',
'Bad Dreams','None','None',
'Natural Cure','None','None',
'Multitype','None','None',
'Victory Star','None','None',
'Overgrow','Bad Company','Contrary',
'Overgrow','Bad Company','Contrary',
'Overgrow','Bad Company','Contrary',
'Blaze','Thick Fat','None',
'Blaze','Thick Fat','None',
'Blaze','Reckless','None',
'Torrent','None','Shell Armor',
'Torrent','None','Shell Armor',
'Shell Armor','None','Torrent',
'Analytic','None','None',
'Analytic','None','None',
'Vital Spirit','None','Run Away',
'Intimidate','None','Sand Rush',
'Intimidate','None','Sand Rush',
'Unburden','Prankster','Limber',
'Unburden','Prankster','Limber',
'Overgrow','None','Gluttony',
'Overgrow','None','Gluttony',
'Blaze','None','Gluttony',
'Blaze','None','Gluttony',
'Torrent','None','Gluttony',
'Torrent','None','Gluttony',
'Telepathy','Synchronize','None',
'Telepathy','Synchronize','None',
'Super Luck','None','Big Pecks',
'Super Luck','None','Big Pecks',
'Super Luck','None','Big Pecks',
'Reckless','None','Sap Sipper',
'Reckless','None','Sap Sipper',
'Sturdy','Solid Rock','Sand Force',
'Sturdy','Solid Rock','Sand Force',
'Sturdy','Solid Rock','Sand Stream',
'Unaware','None','Simple',
'Unaware','None','Simple',
'Sand Rush','Sand Force','Mold Breaker',
'Sand Rush','Sand Force','Mold Breaker',
'Healer','None','Regenerator',
'Guts','Iron Fist','Sheer Force',
'Guts','Iron Fist','Sheer Force',
'Guts','Iron Fist','Sheer Force',
'Swift Swim','None','Water Absorb',
'Swift Swim','None','Water Absorb',
'Swift Swim','None','Water Absorb',
'Guts','Mold Breaker','Inner Focus',
'Sturdy','Mold Breaker','Inner Focus',
'Swarm','Chlorophyll','Overcoat',
'Leaf Guard','Chlorophyll','Overcoat',
'Swarm','Chlorophyll','Overcoat',
'Poison Point','Swarm','Speed Boost',
'Poison Point','Swarm','Speed Boost',
'Poison Point','Swarm','Speed Boost',
'Prankster','Chlorophyll','Infiltrator',
'Prankster','Chlorophyll','Infiltrator',
'Chlorophyll','None','Own Tempo',
'Chlorophyll','None','Own Tempo',
'Reckless','Adaptability','Mold Breaker',
'Intimidate','None','Moxie',
'Intimidate','None','Moxie',
'Intimidate','None','Moxie',
'Inner Focus','None','Hustle',
'Sheer Force','None','Zen Mode',
'Chlorophyll','None','Storm Drain',
'Sturdy','Shell Armor','Weak Armor',
'Sturdy','Shell Armor','Weak Armor',
'Intimidate','None','Moxie',
'Intimidate','None','Moxie',
'Tinted Lens','Magic Guard','Wonder Skin',
'Mummy','None','None',
'Mummy','None','None',
'Solid Rock','Sturdy','Swift Swim',
'Solid Rock','Sturdy','Swift Swim',
'Defeatist','None','None',
'Defeatist','None','None',
'Sticky Hold','None','Aftermath',
'Weak Armor','Sticky Hold','Aftermath',
'Illusion','None','None',
'Illusion','None','None',
'Skill Link','None','Technician',
'Skill Link','None','Technician',
'Shadow Tag','None','Competitive',
'Shadow Tag','None','Competitive',
'Shadow Tag','None','Competitive',
'Regenerator','Magic Guard','Overcoat',
'Regenerator','Magic Guard','Overcoat',
'Regenerator','Magic Guard','Overcoat',
'Keen Eye','None','Hydration',
'No Guard','None','Hydration',
'Weak Armor','None','Snow Cloak',
'Weak Armor','None','Snow Cloak',
'Weak Armor','None','Snow Warning',
'Chlorophyll','None','Serene Grace',
'Chlorophyll','Triage','Serene Grace',
'Static','None','Motor Drive',
'Swarm','Shed Skin','No Guard',
'Swarm','Shell Armor','Overcoat',
'Effect Spore','None','Regenerator',
'Effect Spore','None','Regenerator',
'Cursed Body','None','Water Absorb',
'Cursed Body','None','Water Absorb',
'Healer','Hydration','Regenerator',
'Compound Eyes','Unnerve','Swarm',
'Compound Eyes','Unnerve','Swarm',
'Iron Barbs','None','None',
'Iron Barbs','None','None',
'Clear Body','None','Minus',
'Clear Body','None','Minus',
'Clear Body','None','Minus',
'Levitate','None','None',
'Levitate','None','None',
'Levitate','None','None',
'Analytic','Synchronize','Telepathy',
'Analytic','Synchronize','Telepathy',
'Infiltrator','Shadow Tag','Flame Body',
'Infiltrator','Shadow Tag','Flame Body',
'Infiltrator','Shadow Tag','Flame Body',
'Unnerve','Mold Breaker','Unnerve',
'Unnerve','Mold Breaker','Unnerve',
'Unnerve','Mold Breaker','Unnerve',
'Rattled','Slush Rush','Snow Cloak',
'Swift Swim','Slush Rush','Snow Cloak',
'Levitate','None','None',
'Overcoat','Shell Armor','Hydration',
'Unburden','Sticky Hold','Hydration',
'Static','None','Sand Veil',
'Inner Focus','Regenerator','Reckless',
'Inner Focus','Regenerator','Reckless',
'Rough Skin','Sheer Force','Mold Breaker',
'Iron Fist','No Guard','Klutz',
'Iron Fist','No Guard','Klutz',
'Inner Focus','None','Defiant',
'Inner Focus','None','Defiant',
'Reckless','Soundproof','Sap Sipper',
'Hustle','None','Sheer Force',
'Sheer Force','None','Defiant',
'Big Pecks','Overcoat','Weak Armor',
'Big Pecks','Overcoat','Weak Armor',
'Fatal Precision','None','Gluttony',
'Swarm','Hustle','Truant',
'Hustle','None','None',
'Hustle','None','None',
'Levitate','None','None',
'Swarm','None','Flame Body',
'Swarm','None','Flame Body',
'Inner Focus','None','Justified',
'Inner Focus','None','Justified',
'Inner Focus','None','Justified',
'Prankster','None','Defiant',
'Prankster','None','Defiant',
'Turboblaze','None','None',
'Teravolt','None','None',
'Sheer Force','None','Sand Force',
'Pressure','None','None',
'Inner Focus','None','Justified',
'Serene Grace','None','None',
'Analytic','None','Download',
'Overgrow','None','Bulletproof',
'Overgrow','None','Bulletproof',
'Overgrow','None','Bulletproof',
'Blaze','None','Magician',
'Blaze','None','Magician',
'Blaze','None','Magician',
'Torrent','None','Protean',
'Torrent','None','Protean',
'Torrent','None','Protean',
'Huge Power','None','Cheek Pouch',
'Huge Power','None','Cheek Pouch',
'Keen Eye','None','Gale Wings',
'Flame Body','None','Gale Wings',
'Flame Body','None','Gale Wings',
'Friend Guard','Shield Dust','Compound Eyes',
'Friend Guard','Shed Skin','Friend Guard',
'Friend Guard','Shield Dust','Compound Eyes',
'Unnerve','None','Adaptability',
'Unnerve','None','Adaptability',
'Flower Veil','None','Symbiosis',
'Flower Veil','None','Symbiosis',
'Flower Veil','None','Symbiosis',
'Grass Pelt','None','Sap Sipper',
'Grass Pelt','None','Sap Sipper',
'Iron Fist','Mold Breaker','Scrappy',
'Iron Fist','Mold Breaker','Scrappy',
'Fur Coat','None','None',
'Mystic Charm','None','Own Tempo',
'Mystic Charm','None','Prankster',
'No Guard','None','None',
'No Guard','None','None',
'Stance Change','None','None',
'Healer','Aroma Veil','None',
'Healer','Aroma Veil','None',
'Sweet Veil','Unburden','None',
'Sweet Veil','Unburden','None',
'Bad Company','Infiltrator','Contrary',
'Bad Company','Infiltrator','Contrary',
'Tough Claws','Sniper','Pickpocket',
'Tough Claws','Sniper','Pickpocket',
'Adaptability','None','Poison Point',
'Adaptability','None','Poison Point',
'Mega Launcher','None','None',
'Mega Launcher','None','None',
'Solar Power','None','Dry Skin',
'Solar Power','None','Dry Skin',
'Strong Jaw','None','Sturdy',
'Strong Jaw','None','Rock Head',
'Refrigerate','None','Snow Warning',
'Refrigerate','None','Snow Warning',
'Pixilate','None','Cute Charm',
'Mold Breaker','Unburden','Limber',
'Cheek Pouch','None','Plus',
'Clear Body','None','Sturdy',
'Gooey','Hydration','Sap Sipper',
'Gooey','Hydration','Sap Sipper',
'Gooey','Hydration','Sap Sipper',
'Prankster','None','Magician',
'Natural Cure','Harvest','None',
'Natural Cure','Harvest','None',
'Insomnia','None','None',
'Insomnia','None','None',
'Own Tempo','Ice Body','Sturdy',
'Own Tempo','Ice Body','Sturdy',
'Telepathy','Infiltrator','Aerilate',
'Telepathy','Infiltrator','Aerilate',
'Fairy Aura','None','None',
'Dark Aura','None','None',
'Aura Break','None','None',
'Clear Body','None','None',
'Infiltrator','None','Magician',
'White Smoke','None','Water Absorb',
'Overgrow','None','Long Reach',
'Overgrow','None','Long Reach',
'Overgrow','None','Long Reach',
'Blaze','None','Intimidate',
'Blaze','None','Intimidate',
'Blaze','None','Intimidate',
'Torrent','None','Liquid Voice',
'Torrent','None','Liquid Voice',
'Torrent','None','Liquid Voice',
'Skill Link','None','Pickup',
'Skill Link','None','Pickup',
'Skill Link','None','Sheer Force',
'Adaptability','Strong Jaw','Stakeout',
'Adaptability','Strong Jaw','Stakeout',
'Swarm','None','None',
'Battery','None','None',
'Levitate','None','None',
'Hyper Cutter','Iron Fist','Anger Point',
'Hyper Cutter','Iron Fist','Anger Point',
'Dancer','None','None',
'Sweet Veil','Shield Dust','None',
'Sweet Veil','Shield Dust','None',
'Vital Spirit','None','None',
'Sand Rush','None','None',
'Schooling','None','None',
'Merciless','Limber','Regenerator',
'Merciless','Limber','Regenerator',
'Tangling Hair','Inner Focus','Stamina',
'Tangling Hair','Inner Focus','Stamina',
'Water Bubble','None','None',
'Water Bubble','None','None',
'Sharpness','Bad Company','Contrary',
'Sharpness','Bad Company','Contrary',
'Illuminate','Rain Dish','Effect Spore',
'Illuminate','Rain Dish','Effect Spore',
'Corrosion','None','Oblivious',
'Corrosion','None','Oblivious',
'Fluffy','None','Cute Charm',
'Fluffy','None','Cute Charm',
'Leaf Guard','Oblivious','Sweet Veil',
'Leaf Guard','Oblivious','Sweet Veil',
'Striker','Queenly Majesty','Sweet Veil',
'Triage','None','Natural Cure',
'Inner Focus','Telepathy','Symbiosis',
'Receiver','None','Defiant',
'Wimp Out','None','None',
'Emergency Exit','None','None',
'Water Compaction','None','Sand Veil',
'Water Compaction','None','Sand Veil',
'Unaware','None','Innards Out',
'Battle Armor','None','None',
'RKS System','None','None',
'Shields Down','None','None',
'Comatose','None','None',
'Shell Armor','None','None',
'Iron Barbs','None','Sturdy',
'Disguise','None','None',
'Dazzling','Strong Jaw','Wonder Skin',
'Cloud Nine','None','Berserk',
'Steelworker','None','None',
'Overcoat','Soundproof','Bulletproof',
'Overcoat','Soundproof','Bulletproof',
'Overcoat','Soundproof','Bulletproof',
'Telepathy','None','Electric Surge',
'Telepathy','None','Psychic Surge',
'Telepathy','None','Grassy Surge',
'Telepathy','None','Misty Surge',
'Unaware','None','None',
'Sturdy','None','None',
'Full Metal Body','None','None',
'Shadow Shield','None','None',
'Liquid Ooze','None','Beast Boost',
'Mold Breaker','None','Beast Boost',
'Limber','None','Beast Boost',
'Battery','None','Beast Boost',
'Oblivious','None','Beast Boost',
'Hyper Cutter','None','Beast Boost',
'Thick Fat','None','Beast Boost',
'Prism Armor','None','None',
'Healer','None','Soul-Heart',
'Technician','None','None',
'Unnerve','None','Beast Boost',
'Unnerve','None','Beast Boost',
'Sand Force','None','Beast Boost',
'Insomnia','None','Beast Boost',
'Iron Fist','None','Volt Absorb',
'Magnet Pull','None','None',
'Iron Fist','None','None',
'Overgrow','None','Grassy Surge',
'Overgrow','None','Grassy Surge',
'Overgrow','None','Grassy Surge',
'Blaze','None','Libero',
'Blaze','None','Libero',
'Blaze','None','Libero',
'Torrent','None','Sniper',
'Torrent','None','Sniper',
'Torrent','None','Sniper',
'Cheek Pouch','None','Gluttony',
'Cheek Pouch','None','Gluttony',
'Unnerve','None','Big Pecks',
'Unnerve','None','Big Pecks',
'Unnerve','None','Mirror Armor',
'Swarm','Compound Eyes','Telepathy',
'Swarm','Compound Eyes','Telepathy',
'Swarm','Compound Eyes','Telepathy',
'Run Away','Unburden','Stakeout',
'Run Away','Unburden','Stakeout',
'Cotton Down','None','Regenerator',
'Cotton Down','None','Regenerator',
'Fluffy','None','Bulletproof',
'Fluffy','None','Bulletproof',
'Strong Jaw','Shell Armor','Swift Swim',
'Strong Jaw','Shell Armor','Swift Swim',
'Ball Fetch','None','Rattled',
'Strong Jaw','None','Competitive',
'Heatproof','None','Steam Engine',
'Flame Body','None','Steam Engine',
'Flame Body','None','Steam Engine',
'Ripen','Ripen','Bulletproof',
'Ripen','Gluttony','Hustle',
'Ripen','Thick Fat','Gluttony',
'Infiltrator','None','Sand Spit',
'Infiltrator','None','Sand Spit',
'Gulp Missile','None','None',
'Swift Swim','None','Propeller Tail',
'Swift Swim','None','Propeller Tail',
'Rattled','Static','Klutz',
'Punk Rock','None','Technician',
'Flame Body','White Smoke','Flash Fire',
'Flame Body','White Smoke','Flash Fire',
'Limber','Technician','None',
'Limber','Technician','None',
'Cursed Body','None','Weak Armor',
'Cursed Body','None','Weak Armor',
'Healer','None','Magic Bounce',
'Healer','None','Magic Bounce',
'Healer','None','Magic Bounce',
'Prankster','None','Pickpocket',
'Prankster','None','Pickpocket',
'Prankster','None','Pickpocket',
'Guts','None','Defiant',
'Battle Armor','Steely Spirit','Tough Claws',
'Weak Armor','None','Perish Body',
'Scrappy','None','Scrappy',
'Ice Body','Vital Spirit','Screen Cleaner',
'Wandering Spirit','None','None',
'Sweet Veil','Aroma Veil','Aroma Veil',
'Sweet Veil','Aroma Veil','Aroma Veil',
'Battle Armor','None','Defiant',
'Iron Barbs','None','Electric Surge',
'Ice Scales','None','Shield Dust',
'Ice Scales','None','Shield Dust',
'Power Spot','None','None',
'Ice Face','None','None',
'Synchronize','None','Psychic Surge',
'Hunger Switch','None','None',
'Sheer Force','Heavy Metal','None',
'Sheer Force','Heavy Metal','None',
'Sand Rush','None','Hustle',
'Slush Rush','None','Static',
'Sand Rush','None','Strong Jaw',
'Slush Rush','None','Ice Body',
'Light Metal','Stalwart','Heavy Metal',
'Clear Body','Infiltrator','Cursed Body',
'Clear Body','Infiltrator','Cursed Body',
'Clear Body','Infiltrator','Cursed Body',
'Intrepid Sword','None','None',
'Dauntless Shield','None','None',
'Pressure','None','None',
'Inner Focus','None','None',
'Unseen Fist','None','None',
'Leaf Guard','None','None',
'Transistor','None','None',
"Dragon's Maw",'None','None',
'Unnerve','None','Chilling Neigh',
'Unnerve','None','Grim Neigh',
'Unnerve','None','None',
'Intimidate','None','Sap Sipper',
'Swarm','Sheer Force','Steadfast',
'Guts','Unnerve','Bulletproof',
'Swift Swim','Adaptability','Mold Breaker',
'Poison Touch','Unburden','Poison Touch',
'Intimidate','Swift Swim','Poison Point',
'Bad Company','None','Contrary',
'Thick Fat','Thick Fat','None',
'Tough Claws','Tough Claws','None',
'Drought','Drought','None',
'Mega Launcher','Mega Launcher','None',
'Adaptability','Adaptability','None',
'No Guard','No Guard','None',
'Trace','Trace','None',
'Shell Armor','Shell Armor','None',
'Shadow Tag','Shadow Tag','None',
'Parental Bond','Parental Bond','None',
'Aerilate','Aerilate','None',
'Mold Breaker','Mold Breaker','None',
'Tough Claws','Tough Claws','None',
'Steadfast','Steadfast','None',
'Insomnia','Insomnia','None',
'Mold Breaker','Mold Breaker','None',
'Sand Force','Sand Force','None',
'Technician','Technician','None',
'Skill Link','Skill Link','None',
'Solar Power','Solar Power','None',
'Intimidate','Intimidate','Sand Stream',
'Limber','Limber','Lightning Rod',
'Striker','Striker','Speed Boost',
'Swift Swim','Swift Swim','None',
'Pixilate','Pixilate','None',
'Magic Bounce','Magic Bounce','None',
'Huge Power','Huge Power','None',
'Filter','Filter','None',
'Pure Power','Pure Power','None',
'Intimidate','Intimidate','None',
'Strong Jaw','Strong Jaw','None',
'Sheer Force','Sheer Force','None',
'Pixilate','Pixilate','None',
'Prankster','Prankster','None',
'Magic Bounce','Magic Bounce','None',
'Refrigerate','Refrigerate','None',
'Aerilate','Aerilate','None',
'Tough Claws','Tough Claws','None',
'Levitate','Levitate','None',
'Levitate','Levitate','None',
'Scrappy','Scrappy','None',
'Sand Force','Sand Force','None',
'Adaptability','Adaptability','None',
'Reckless','Reckless','Snow Warning',
'Inner Focus','Inner Focus','None',
'Healer','Healer','None',
'Magic Bounce','Magic Bounce','None',
'Delta Stream','Delta Stream','None',
'Primordial Sea','Primordial Sea','None',
'Desolate Land','Desolate Land','None',
'Thick Fat','None','Gluttony',
'Thick Fat','None','Hustle',
'Surge Surfer','None','None',
'Slush Rush','None','Snow Cloak',
'Slush Rush','None','Snow Cloak',
'Slush Rush','None','Snow Warning',
'Slush Rush','None','Snow Warning',
'Tangling Hair','None','Sand Force',
'Tangling Hair','None','Sand Force',
'Technician','None','Rattled',
'Fur Coat','None','Technician',
'Galvanize','Sturdy','Magnet Pull',
'Galvanize','Sturdy','Magnet Pull',
'Galvanize','Sturdy','Magnet Pull',
'Poison Touch','Gluttony','Power of Alchemy',
'Poison Touch','Gluttony','Power of Alchemy',
'Harvest','None','None',
'Rock Head','None','Lightning Rod',
'Unnerve','Tough Claws','Unnerve',
'Pastel Veil','None','Anticipation',
'Pastel Veil','None','Anticipation',
'Gluttony','Own Tempo','Regenerator',
'Quick Draw','Own Tempo','Regenerator',
'Scrappy','None','Scrappy',
'Levitate','Neutralizing Gas','Misty Surge',
'Ice Body','Vital Spirit','Screen Cleaner',
'Keen Eye','None','Competitive',
'Keen Eye','None','Defiant',
'Keen Eye','None','Berserk',
'Curious Medicine','Own Tempo','Regenerator',
'Weak Armor','None','Cursed Body',
'Quick Feet','None','Gluttony',
'Quick Feet','None','Gluttony',
'Inner Focus','None','Hustle',
'Gorilla Tactics','None','Zen Mode',
'Wandering Spirit','None','None',
'Filter','None','Mimicry',
'Rock Head','None','Intimidate',
'Rock Head','None','Intimidate',
'Soundproof','Static','Aftermath',
'Soundproof','Static','Aftermath',
'Blaze','None','Flash Fire',
'Intimidate','Swift Swim','Poison Point',
'Poison Touch','Unburden','Poison Touch',
'Sharpness','None','Torrent',
'Chlorophyll','Own Tempo','Hustle',
'Illusion','None','None',
'Illusion','None','None',
'Sheer Force','Tinted Lens','Keen Eye',
'Gooey','Shell Armor','Sap Sipper',
'Gooey','Shell Armor','Sap Sipper',
'Strong Jaw','Ice Body','Sturdy',
'Overgrow','Scrappy','Scrappy',
'Static','None','Lightning Rod',
'Static','None','Lightning Rod',
'Static','None','Lightning Rod',
'Static','None','Lightning Rod',
'Static','None','Lightning Rod',
'Static','None','Lightning Rod',
'Static','None','Lightning Rod',
'Static','None','Lightning Rod',
'Static','None','Lightning Rod',
'Static','None','Lightning Rod',
'Static','None','Lightning Rod',
'Static','None','Lightning Rod',
'Static','None','Lightning Rod',
'Static','None','Lightning Rod',
'Static','None','Lightning Rod',
'Levitate','None','None',
'Levitate','None','None',
'Levitate','None','None',
'Levitate','None','None',
'Levitate','None','None',
'Levitate','None','None',
'Levitate','None','None',
'Levitate','None','None',
'Levitate','None','None',
'Levitate','None','None',
'Levitate','None','None',
'Levitate','None','None',
'Levitate','None','None',
'Levitate','None','None',
'Levitate','None','None',
'Levitate','None','None',
'Levitate','None','None',
'Levitate','None','None',
'Levitate','None','None',
'Levitate','None','None',
'Levitate','None','None',
'Levitate','None','None',
'Levitate','None','None',
'Levitate','None','None',
'Levitate','None','None',
'Levitate','None','None',
'Levitate','None','None',
'Forecast','None','None',
'Forecast','None','None',
'Forecast','None','None',
'Synchronize','None','None',
'Synchronize','None','None',
'Synchronize','None','None',
'Overcoat','None','Overcoat',
'Overcoat','None','Overcoat',
'Overcoat','None','Overcoat',
'Overcoat','None','Overcoat',
'Flower Gift','None','None',
'Sticky Hold','Sand Force','Storm Drain',
'Sticky Hold','Sand Force','Storm Drain',
'Levitate','None','None',
'Levitate','None','None',
'Levitate','None','None',
'Levitate','None','None',
'Levitate','None','None',
'Pressure','None','Telepathy',
'Pressure','None','Telepathy',
'Levitate','None','None',
'Serene Grace','None','None',
'Multitype','None','None',
'Multitype','None','None',
'Multitype','None','None',
'Multitype','None','None',
'Multitype','None','None',
'Multitype','None','None',
'Multitype','None','None',
'Multitype','None','None',
'Multitype','None','None',
'Multitype','None','None',
'Multitype','None','None',
'Multitype','None','None',
'Multitype','None','None',
'Multitype','None','None',
'Multitype','None','None',
'Multitype','None','None',
'Multitype','None','None',
'Rock Head','Adaptability','Adaptability',
'Rattled','Adaptability','Mold Breaker',
'Sheer Force','None','Zen Mode',
'Gorilla Tactics','None','Zen Mode',
'Chlorophyll','None','Serene Grace',
'Chlorophyll','None','Serene Grace',
'Chlorophyll','None','Serene Grace',
'Chlorophyll','Triage','Serene Grace',
'Chlorophyll','Triage','Serene Grace',
'Chlorophyll','Triage','Serene Grace',
'Regenerator','None','None',
'Volt Absorb','None','None',
'Intimidate','None','None',
'Overcoat','None','None',
'Turboblaze','None','None',
'Teravolt','None','None',
'Inner Focus','None','Justified',
'Serene Grace','None','None',
'Analytic','None','Download',
'Analytic','None','Download',
'Analytic','None','Download',
'Analytic','None','Download',
'Battle Bond','None','None',
'Battle Bond','None','None',
'Shield Dust','Compound Eyes','Friend Guard',
'Shield Dust','Compound Eyes','Friend Guard',
'Shield Dust','Compound Eyes','Friend Guard',
'Shield Dust','Compound Eyes','Friend Guard',
'Shield Dust','Compound Eyes','Friend Guard',
'Shield Dust','Compound Eyes','Friend Guard',
'Shield Dust','Compound Eyes','Friend Guard',
'Shield Dust','Compound Eyes','Friend Guard',
'Shield Dust','Compound Eyes','Friend Guard',
'Shield Dust','Compound Eyes','Friend Guard',
'Shield Dust','Compound Eyes','Friend Guard',
'Shield Dust','Compound Eyes','Friend Guard',
'Shield Dust','Compound Eyes','Friend Guard',
'Shield Dust','Compound Eyes','Friend Guard',
'Shield Dust','Compound Eyes','Friend Guard',
'Shield Dust','Compound Eyes','Friend Guard',
'Shield Dust','Compound Eyes','Friend Guard',
'Shield Dust','Compound Eyes','Friend Guard',
'Shield Dust','Compound Eyes','Friend Guard',
'Flower Veil','None','Symbiosis',
'Flower Veil','None','Symbiosis',
'Flower Veil','None','Symbiosis',
'Flower Veil','None','Symbiosis',
'Flower Veil','None','Symbiosis',
'Flower Veil','None','Symbiosis',
'Flower Veil','None','Symbiosis',
'Flower Veil','None','Symbiosis',
'Flower Veil','None','Symbiosis',
'Flower Veil','None','Symbiosis',
'Flower Veil','None','Symbiosis',
'Flower Veil','None','Symbiosis',
'Flower Veil','None','Symbiosis',
'Fur Coat','None','None',
'Fur Coat','None','None',
'Fur Coat','None','None',
'Fur Coat','None','None',
'Fur Coat','None','None',
'Fur Coat','None','None',
'Fur Coat','None','None',
'Fur Coat','None','None',
'Fur Coat','None','None',
'Mystic Charm','None','Competitive',
'Stance Change','None','None',
'Insomnia','Insomnia','Insomnia',
'Insomnia','Insomnia','Insomnia',
'Insomnia','Insomnia','Insomnia',
'Insomnia','Insomnia','Insomnia',
'Insomnia','Insomnia','Insomnia',
'Insomnia','Insomnia','Insomnia',
'Fairy Aura','None','None',
'Aura Break','None','None',
'Power Construct','None','None',
'Power Construct','None','None',
'Power Construct','None','None',
'Infiltrator','None','Magician',
'Dancer','None','None',
'Dancer','None','None',
'Dancer','None','None',
'Own Tempo','None','None',
'No Guard','None','None',
'Tough Claws','None','None',
'Schooling','None','None',
'RKS System','None','None',
'RKS System','None','None',
'RKS System','None','None',
'RKS System','None','None',
'RKS System','None','None',
'RKS System','None','None',
'RKS System','None','None',
'RKS System','None','None',
'RKS System','None','None',
'RKS System','None','None',
'RKS System','None','None',
'RKS System','None','None',
'RKS System','None','None',
'RKS System','None','None',
'RKS System','None','None',
'RKS System','None','None',
'RKS System','None','None',
'Shields Down','None','None',
'Shields Down','None','None',
'Shields Down','None','None',
'Shields Down','None','None',
'Shields Down','None','None',
'Shields Down','None','None',
'Shields Down','None','None',
'Shields Down','None','None',
'Shields Down','None','None',
'Shields Down','None','None',
'Shields Down','None','None',
'Shields Down','None','None',
'Shields Down','None','None',
'Disguise','None','None',
'Prism Armor','None','None',
'Prism Armor','None','None',
'Neuroforce','None','None',
'Healer','None','Soul-Heart',
'Gulp Missile','None','None',
'Gulp Missile','None','None',
'Punk Rock','None','Technician',
'Cursed Body','None','Weak Armor',
'Cursed Body','None','Weak Armor',
'Sweet Veil','Aroma Veil','Aroma Veil',
'Sweet Veil','Aroma Veil','Aroma Veil',
'Sweet Veil','Aroma Veil','Aroma Veil',
'Sweet Veil','Aroma Veil','Aroma Veil',
'Sweet Veil','Aroma Veil','Aroma Veil',
'Sweet Veil','Aroma Veil','Aroma Veil',
'Sweet Veil','Aroma Veil','Aroma Veil',
'Sweet Veil','Aroma Veil','Aroma Veil',
'Ice Face','None','None',
'Synchronize','Synchronize','Psychic Surge',
'Hunger Switch','None','None',
'Intrepid Sword','None','None',
'Dauntless Shield','None','None',
'Pressure','None','None',
'Unseen Fist','None','None',
'Leaf Guard','None','None',
'As One (Glastrier)','None','None',
'As One (Spectrier)','None','None',
'Sweet Veil','Aroma Veil','Aroma Veil',
'Sweet Veil','Aroma Veil','Aroma Veil',
'Sweet Veil','Aroma Veil','Aroma Veil',
'Sweet Veil','Aroma Veil','Aroma Veil',
'Sweet Veil','Aroma Veil','Aroma Veil',
'Sweet Veil','Aroma Veil','Aroma Veil',
'Sweet Veil','Aroma Veil','Aroma Veil',
'Sweet Veil','Aroma Veil','Aroma Veil',
'Sweet Veil','Aroma Veil','Aroma Veil',
'Sweet Veil','Aroma Veil','Aroma Veil',
'Sweet Veil','Aroma Veil','Aroma Veil',
'Sweet Veil','Aroma Veil','Aroma Veil',
'Sweet Veil','Aroma Veil','Aroma Veil',
'Sweet Veil','Aroma Veil','Aroma Veil',
'Sweet Veil','Aroma Veil','Aroma Veil',
'Sweet Veil','Aroma Veil','Aroma Veil',
'Sweet Veil','Aroma Veil','Aroma Veil',
'Sweet Veil','Aroma Veil','Aroma Veil',
'Sweet Veil','Aroma Veil','Aroma Veil',
'Sweet Veil','Aroma Veil','Aroma Veil',
'Sweet Veil','Aroma Veil','Aroma Veil',
'Sweet Veil','Aroma Veil','Aroma Veil',
'Sweet Veil','Aroma Veil','Aroma Veil',
'Sweet Veil','Aroma Veil','Aroma Veil',
'Sweet Veil','Aroma Veil','Aroma Veil',
'Sweet Veil','Aroma Veil','Aroma Veil',
'Sweet Veil','Aroma Veil','Aroma Veil',
'Sweet Veil','Aroma Veil','Aroma Veil',
'Sweet Veil','Aroma Veil','Aroma Veil',
'Sweet Veil','Aroma Veil','Aroma Veil',
'Sweet Veil','Aroma Veil','Aroma Veil',
'Sweet Veil','Aroma Veil','Aroma Veil',
'Sweet Veil','Aroma Veil','Aroma Veil',
'Sweet Veil','Aroma Veil','Aroma Veil',
'Sweet Veil','Aroma Veil','Aroma Veil',
'Sweet Veil','Aroma Veil','Aroma Veil',
'Sweet Veil','Aroma Veil','Aroma Veil',
'Sweet Veil','Aroma Veil','Aroma Veil',
'Sweet Veil','Aroma Veil','Aroma Veil',
'Sweet Veil','Aroma Veil','Aroma Veil',
'Sweet Veil','Aroma Veil','Aroma Veil',
'Sweet Veil','Aroma Veil','Aroma Veil',
'Sweet Veil','Aroma Veil','Aroma Veil',
'Sweet Veil','Aroma Veil','Aroma Veil',
'Sweet Veil','Aroma Veil','Aroma Veil',
'Sweet Veil','Aroma Veil','Aroma Veil',
'Sweet Veil','Aroma Veil','Aroma Veil',
'Sweet Veil','Aroma Veil','Aroma Veil',
'Sweet Veil','Aroma Veil','Aroma Veil',
'Sweet Veil','Aroma Veil','Aroma Veil',
'Sweet Veil','Aroma Veil','Aroma Veil',
'Sweet Veil','Aroma Veil','Aroma Veil',
'Sweet Veil','Aroma Veil','Aroma Veil',
'Sweet Veil','Aroma Veil','Aroma Veil',
'Sweet Veil','Aroma Veil','Aroma Veil',
'Overgrow','None','Protean',
'Overgrow','None','Protean',
'Overgrow','None','Protean',
'Blaze','None','Unaware',
'Blaze','None','Unaware',
'Blaze','None','Unaware',
'Torrent','None','Moxie',
'Torrent','None','Moxie',
'Torrent','None','Moxie',
'Aroma Veil','Thick Fat','Gluttony',
'Lingering Aroma','Thick Fat','Gluttony',
'Thick Fat','None','Gluttony',
'Insomnia','None','Stakeout',
'Insomnia','None','Stakeout',
'Swarm','None','Tinted Lens',
'Swarm','None','Tinted Lens',
'Iron Fist','None','Static',
'Iron Fist','None','Volt Absorb',
'Iron Fist','None','Volt Absorb',
'Own Tempo','None','Run Away',
'Technician','None','Friend Guard',
'Technician','None','Friend Guard',
'Own Tempo','None','Klutz',
'Heatproof','None','Well-Baked Body',
'Early Bird','None','Harvest',
'Early Bird','None','Harvest',
'Harvest','None','Seed Sower',
'Intimidate','Hustle','Guts',
'Intimidate','Hustle','Guts',
'Intimidate','Hustle','Guts',
'Intimidate','Hustle','Guts',
'Purifying Salt','Clear Body','Sturdy',
'Purifying Salt','Clear Body','Sturdy',
'Purifying Salt','Clear Body','Sturdy',
'Flame Body','None','Flash Fire',
'Mega Launcher','None','Weak Armor',
'Sharpness','None','Weak Armor',
'Own Tempo','Static','Damp',
'Electromorphosis','None','Static',
'Wind Power','None','Competitive',
'Wind Power','None','Competitive',
'Intimidate','Run Away','Stakeout',
'Intimidate','Guard Dog','Stakeout',
'Unburden','Prankster','Poison Touch',
'Unburden','Prankster','Poison Touch',
'Infiltrator','None','Wind Rider',
'Infiltrator','None','Wind Rider',
'Mycelium Might','None','None',
'Mycelium Might','None','None',
'Regenerator','Shell Armor','Anger Shell',
'Chlorophyll','None','Klutz',
'Chlorophyll','None','Moody',
'Compound Eyes','None','Shed Skin',
'Synchronize','None','Telepathy',
'Speed Boost','None','None',
'Speed Boost','None','Opportunist',
'Mold Breaker','Own Tempo','Pickpocket',
'Mold Breaker','Own Tempo','Pickpocket',
'Mold Breaker','Own Tempo','Pickpocket',
'Arena Trap','None','Sand Veil',
'Arena Trap','None','Sand Veil',
'Rocky Payload','None','Big Pecks',
'Water Veil','None','None',
'Zero to Hero','None','None',
'Zero to Hero','None','None',
'Overcoat','None','None',
'Overcoat','Filter','None',
'Regenerator','None','Shed Skin',
'Earth Eater','None','Sand Veil',
'Corrosion','None','Toxic Debris',
'Corrosion','None','Toxic Debris',
'Sand Rush','None','Fluffy',
'Sand Rush','None','Fluffy',
'Scrappy','None','Costar',
'Thick Fat','Snow Cloak','Sheer Force',
'Thick Fat','Slush Rush','Sheer Force',
'Sharpness','None','Mold Breaker',
'Unaware','None','Oblivious',
'Commander','None','Storm Drain',
'Commander','None','Storm Drain',
'Commander','None','Storm Drain',
'Vital Spirit','Inner Focus','Defiant',
'Poison Point','Unaware','Water Absorb',
'Cud Chew','Armor Tail','Sap Sipper',
'Rattled','None','Serene Grace',
'Rattled','None','Serene Grace',
'Supreme Overlord','None','Defiant',
'Protosynthesis','None','None',
'Protosynthesis','None','None',
'Protosynthesis','None','None',
'Protosynthesis','None','None',
'Protosynthesis','None','None',
'Protosynthesis','None','None',
'Quark Drive','None','None',
'Quark Drive','None','None',
'Quark Drive','None','None',
'Quark Drive','None','None',
'Quark Drive','None','None',
'Quark Drive','None','None',
'Ice Body','None','Thermal Exchange',
'Ice Body','None','Thermal Exchange',
'Ice Body','None','Thermal Exchange',
'Rattled','None','None',
'Run Away','None','None',
'Good As Gold','None','None',
'Tablets of Ruin','None','None',
'Sword of Ruin','None','None',
'Vessel of Ruin','None','None',
'Beads of Ruin','None','None',
'Protosynthesis','None','None',
'Quark Drive','None','None',
'Orichalum Pulse','None','None',
'Hadron Engine','None','None',
'Intimidate','None','Cud Chew',
'Intimidate','None','Cud Chew',
'Intimidate','None','Cud Chew',
'Poison Point','Unaware','Water Absorb',
'Protosynthesis','None','None',
'Quark Drive','None','None',
'Supersweet Syrup','Sticky Hold','Gluttony',
'Hospitality','None','Heatproof',
'Hospitality','None','Heatproof',
'Hospitality','None','Heatproof',
'Hospitality','None','Heatproof',
'Toxic Chain','None','Guard Dog',
'Toxic Chain','None','Frisk',
'Toxic Chain','None','Technician',
'Inner Focus','None','None',
'Water Veil','None','None',
'Mold Breaker','None','None',
'Sturdy','None','None',
'Embody Aspect (Teal)','None','None',
'Embody Aspect (Wellspring)','None','None',
'Embody Aspect (Hearthflame)','None','None',
'Embody Aspect (Cornerstone)','None','None',
"Mind's Eye",'None','None',
'Stalwart','Stalwart','Stamina',
'Supersweet Syrup','Sticky Hold','Regenerator',
'Protosynthesis','None','None',
'Protosynthesis','None','None',
'Quark Drive','None','None',
'Quark Drive','None','None',
'Tera Shift','None','None',
'Tera Shell','None','None',
'Teraform Zero','None','None',
'Poison Puppeteer','None','None',}

nature = {"Hardy","Lonely","Brave","Adamant","Naughty",
			"Bold","Docile","Relaxed","Impish","Lax",
			"Timid","Hasty","Serious","Jolly","Naive",
			"Modest","Mild","Quiet","Bashful","Rash",
			"Calm","Gentle","Sassy","Careful","Quirky"}

charmap = { [0]=
	" ", "À", "Á", "Â", "Ç", "È", "É", "Ê", "Ë", "Ì", "こ", "Î", "Ï", "Ò", "Ó", "Ô",
	"Œ", "Ù", "Ú", "Û", "Ñ", "ß", "à", "á", "ね", "ç", "è", "é", "ê", "ë", "ì", "ま",
	"î", "ï", "ò", "ó", "ô", "œ", "ù", "ú", "û", "ñ", "º", "ª", "�", "&", "+", "あ",
	"ぃ", "ぅ", "ぇ", "ぉ", "v", "=", "ょ", "が", "ぎ", "ぐ", "げ", "ご", "ざ", "じ", "ず", "ぜ",
	"ぞ", "だ", "ぢ", "づ", "で", "ど", "ば", "び", "ぶ", "べ", "ぼ", "ぱ", "ぴ", "ぷ", "ぺ", "ぽ",
	"っ", "¿", "¡", "P\u{200d}k", "M\u{200d}n", "P\u{200d}o", "K\u{200d}é", "�", "�", "�", "Í", "%", "(", ")", "セ", "ソ",
	"タ", "チ", "ツ", "テ", "ト", "ナ", "ニ", "ヌ", "â", "ノ", "ハ", "ヒ", "フ", "ヘ", "ホ", "í",
	"ミ", "ム", "メ", "モ", "ヤ", "ユ", "ヨ", "ラ", "リ", "⬆", "⬇", "⬅", "➡", "ヲ", "ン", "ァ",
	"ィ", "ゥ", "ェ", "ォ", "ャ", "ュ", "ョ", "ガ", "ギ", "グ", "ゲ", "ゴ", "ザ", "ジ", "ズ", "ゼ",
	"ゾ", "ダ", "ヂ", "ヅ", "デ", "ド", "バ", "ビ", "ブ", "ベ", "ボ", "パ", "ピ", "プ", "ペ", "ポ",
	"ッ", "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "!", "?", ".", "-", "・",
	"…", "“", "”", "‘", "’", "♂", "♀", "$", ",", "×", "/", "A", "B", "C", "D", "E",
	"F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U",
	"V", "W", "X", "Y", "Z", "a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k",
	"l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z", "▶",
	":", "Ä", "Ö", "Ü", "ä", "ö", "ü", "⬆", "⬇", "⬅", "�", "�", "�", "�", "�", ""
}

-- 6 is placeholder
curve={ 3,3,3,3,3,3,3,3,3,0,0,0,0,0,0,3,3,3,0,0,0,0,0,0,0,0,0,0,3,3,3,3,3,3,4,4,0,0,4,4,0,0,3,3,3,0,0,0,0,0,0,0,0,0,0,0,0,5,5,3,3,3,3,3,3,3
,3,3,3,3,3,5,5,3,3,3,0,0,0,0,0,0,0,0,0,0,0,0,0,5,5,3,3,3,0,0,0,0,0,0,0,5,5,0,0,0,0,0,0,0,5,5,4,0,0,0,0,0,0,5,5,0,0,0,0,0,5,5,5,5,5,0,0,0,0
,0,0,0,0,0,0,5,5,5,5,5,5,5,5,5,3,3,3,3,3,3,3,3,3,3,0,0,0,0,4,4,4,4,0,5,5,0,4,4,4,4,0,0,3,3,3,3,4,4,0,3,3,3,3,4,3,3,0,0,0,0,0,3,0,4,0,0,0,0
,0,0,3,0,4,4,0,0,3,5,3,0,0,0,0,5,5,4,0,0,4,5,5,5,5,0,0,0,0,5,4,0,0,0,0,0,5,4,5,5,5,5,5,5,5,5,3,3,3,3,3,3,3,3,3,3,0,0,0,0,0,0,0,0,0,3,3,3,3
,3,3,3,3,0,0,5,5,5,0,0,2,2,5,5,5,1,1,1,3,3,3,2,2,4,0,4,4,3,4,5,5,5,0,0,5,5,0,0,1,2,3,2,2,5,5,2,2,0,0,0,4,4,4,3,3,3,3,3,1,1,1,2,4,4,0,0,2,2
,0,0,1,1,1,1,1,1,0,3,4,4,4,4,5,4,3,0,0,0,3,3,3,1,1,1,5,4,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3,3,3,3,3,1,1,1,1
,0,0,0,3,3,0,0,0,0,0,0,0,4,2,2,0,0,4,3,4,4,4,0,0,0,0,0,0,4,3,0,5,5,5,5,3,3,5,5,5,5,0,0,5,1,1,5,5,5,3,0,0,5,0,0,0,4,0,0,0,3,5,0,5,0,4,0,0,5
,5,5,5,5,5,5,5,5,5,5,5,3,5,5,3,3,3,3,3,3,3,3,3,0,0,3,3,3,0,0,0,0,0,0,0,0,4,4,3,3,3,0,0,3,3,3,0,0,0,0,4,3,3,3,3,3,3,0,0,3,3,3,3,3,3,0,0,0,0
,0,3,3,3,3,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3,3,4,4,3,3,3,3,3,3,0,0,5,5,5,0,0,0,0,0,0,0,0,0,4,0,0,0,0,3,3,3,5,5,5,0,0,3,3,3,5,5,5,0,0,0,0,0,0
,3,3,0,0,0,0,0,0,5,5,5,5,0,0,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,3,3,3,3,3,3,3,3,3,0,0,3,3,3,0,0,0,3,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
,0,0,0,0,5,5,0,0,0,0,0,0,0,0,0,5,5,5,5,4,0,0,0,0,0,0,0,0,5,5,5,5,5,5,3,3,3,3,3,3,3,3,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,4,0,0,0,0,0,0,0,0,0,0
,0,0,0,0,3,3,3,4,5,5,0,0,0,0,4,5,5,3,5,0,0,0,0,0,0,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,3,3,3,3,3,3,3,3,3,0,0,3,3,3,0,0
,0,4,4,0,0,0,0,0,0,4,4,3,3,3,1,1,1,0,0,0,5,5,3,3,0,0,3,3,0,0,5,5,5,0,0,0,0,0,4,0,0,0,0,0,0,0,0,0,5,5,4,0,0,0,5,5,5,5,0,5,5,5,5,5,5,5,5,5,5
,5,5,5,5,5,0,0,0,3,0,5,3,3,3,3,0,3,3,0,3,0,5,5,5,5,5,3,0,0,5,5,5,3,3,3,5,3,4,5,0,5,5,0,1,4,3,0,5,5,5,5,0,5,3,5,5,4,5,5,5,5,0,0,0,0,0,0,0,0
,0,0,0,3,3,3,0,0,5,0,0,0,0,0,0,0,0,0,0,5,5,5,0,4,0,0,3,3,0,0,5,5,6,0,0,3,0,3,3,0,3,3,5,5,5,0,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,5,5,5,0,0,0,0,0,0,0,0,0,0,0,0,5,5,5,3,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,0,0,3,3,0,0,0,0,0,0,5
,5,5,5,5,5,5,5,5,5,5,5,3,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,5,5,5,5,5,5,0,0,0,0
,0,0,4,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,0,0,0,0,0,0,0,0,0,0,0,0,0,0,5,5,5,5,0,0,3,0,0,0,0,0,0,0,0,0,0,0,0,5,4,0,5,5,5,5,5,5,5,5,0,0,0,0,0
,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3,3,3,3,3,3,3,3,3,0,0,0,1,1,0,0,0,0,0,4
,4,4,3,3,3,3,3,1,1,1,1,3,3,3,5,5,5,0,0,3,3,3,3,3,3,0,0,3,3,0,0,0,4,4,3,3,3,3,3,0,0,5,5,5,5,0,0,3,5,3,3,3,3,3,3,3,4,5,3,3,3,0,0,0,0,0,0,5,5
,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,0,5,5,1,0,0,0,0,5,5,5,5,5,5,5,5,5,5,5,0,0,1,5,5,5,5,5,5,5,5}

local terminator=0xFF
local monNameLength=10
local playerNameLength=10
local boxMonSize=80
local partyMonSize=100
local speciesStructSize=256

local partyCount=0x020337dd -- partyCount
local partyloc=0x02033a3c -- gPlayerParty
local storageLoc=0x0300391c -- gPokemonStorage
local speciesInfo=0x086699b0 -- gSpeciesInfo

function getCurve(n)
	return emu:read8(speciesInfo+(speciesStructSize*n)+21)
end
function slowCurve(n)
    return math.floor((5*(n^3))/4)
end
function fastCurve(n)
    return math.floor((4*(n^3))/5)
end
function medfastCurve(n)
    return n^3
end
function medslowCurve(n)
    return math.floor((6 * (n)^3) / 5) - (15 * (n)^2) + (100 * n) - 140
end
function erraticCurve(n)
    if (n<=50) then
        return math.floor(((100 - n)*n^3)/50)
    end
    if (n<=68) then
        return math.floor(((150 - n)*n^3)/100)
    end
    if (n<=98) then
        return math.floor(math.floor((1911 - 10 * n) / 3) * n^3 / 500)
    end
    return math.floor((160 - n) * n^3 / 100)
end
function flutuatingCurve(n)
	if (n<15) then
	  return math.floor((math.floor((n + 1) / 3) + 24) * n^3 / 50)
	end
	if (n<=36) then
		return math.floor((n + 14) * n^3 / 50)
	end
	return math.floor((math.floor(n / 2) + 32) * n^3 / 50)
end

function calcLevel(exp, species)
	level = 1
	while (exp>=expRequired(species, level+1)) do
		level=level+1
	end
	return level
end

function expRequired(species, level)
	expCurve = curve[species]
	if (expCurve == 0) then return medfastCurve(level) end
	if (expCurve == 1) then return erraticCurve(level) end
	if (expCurve == 2) then return flutuatingCurve(level) end
	if (expCurve == 3) then return medslowCurve(level) end
	if (expCurve == 4) then return fastCurve(level) end
	if (expCurve == 5) then return slowCurve(level) end
	if (expCurve > 5) then return medfastCurve(level) end
end

function getParty()
	local party = {}
	local monStart = partyloc
	for i = 1, emu:read8(partyCount) + 1 do
		party[i] = readPartyMon(monStart)
		monStart = monStart + partyMonSize
	end
	return party
end

function toString(rawstring)
	local string = ""
	for _, char in ipairs({rawstring:byte(1, #rawstring)}) do
		if char == terminator then
			break
		end
		string = string..charmap[char]
	end
	return string
end

function _read16BE(emu, address)
	return (emu:read8(address) << 8) | emu:read8(address + 1)
end

function readBoxMon(address)
	local mon = {}
	mon.personality = emu:read32(address + 0)
	mon.otId = emu:read32(address + 4)
	mon.nickname = toString(emu:readRange(address + 8, monNameLength))
	mon.language = emu:read8(address + 18)

	local flags = emu:read8(address + 19)
	mon.isBadEgg = flags & 1
	mon.hasSpecies = (flags >> 1) & 1
	mon.isEgg = (flags >> 2) & 1
	mon.otName = toString(emu:readRange(address + 20, playerNameLength))
	mon.markings = emu:read8(address + 27)

	local key = mon.otId ~ mon.personality
	local substructSelector = {
		[ 0] = {0, 1, 2, 3},
		[ 1] = {0, 1, 3, 2},
		[ 2] = {0, 2, 1, 3},
		[ 3] = {0, 3, 1, 2},
		[ 4] = {0, 2, 3, 1},
		[ 5] = {0, 3, 2, 1},
		[ 6] = {1, 0, 2, 3},
		[ 7] = {1, 0, 3, 2},
		[ 8] = {2, 0, 1, 3},
		[ 9] = {3, 0, 1, 2},
		[10] = {2, 0, 3, 1},
		[11] = {3, 0, 2, 1},
		[12] = {1, 2, 0, 3},
		[13] = {1, 3, 0, 2},
		[14] = {2, 1, 0, 3},
		[15] = {3, 1, 0, 2},
		[16] = {2, 3, 0, 1},
		[17] = {3, 2, 0, 1},
		[18] = {1, 2, 3, 0},
		[19] = {1, 3, 2, 0},
		[20] = {2, 1, 3, 0},
		[21] = {3, 1, 2, 0},
		[22] = {2, 3, 1, 0},
		[23] = {3, 2, 1, 0},
	}

	local pSel = substructSelector[mon.personality % 24]
	local ss0 = {}
	local ss1 = {}
	local ss2 = {}
	local ss3 = {}

	for i = 0, 2 do
		ss0[i] = emu:read32(address + 32 + pSel[1] * 12 + i * 4) ~ key
		ss1[i] = emu:read32(address + 32 + pSel[2] * 12 + i * 4) ~ key
		ss2[i] = emu:read32(address + 32 + pSel[3] * 12 + i * 4) ~ key
		ss3[i] = emu:read32(address + 32 + pSel[4] * 12 + i * 4) ~ key
	end

	mon.species = ss0[0] & 0x7FF
	mon.heldItem = ss0[0] >> 16
	mon.experience = ss0[1] & 0x1FFFFF
	mon.ppBonuses = ss0[2] & 0xFF
	mon.friendship = (ss0[2] >> 8) & 0xFF

	mon.moves = {
		ss1[0] & 0xFFFF,
		ss1[0] >> 16,
		ss1[1] & 0x7FF,
		ss1[1] >> 16
	}

	-- mon.hiddenNature = (ss1[1] >> 11) & 0x1F
	-- console:log(string.format("%d", mon.hiddenNature))

	mon.pp = {
		ss1[2] & 0xFF,
		(ss1[2] >> 8) & 0xFF,
		(ss1[2] >> 16) & 0xFF,
		ss1[2] >> 24
	}

	mon.hpEV = ss2[0] & 0xFF
	mon.attackEV = (ss2[0] >> 8) & 0xFF
	mon.defenseEV = (ss2[0] >> 16) & 0xFF
	mon.speedEV = ss2[0] >> 24
	mon.spAttackEV = ss2[1] & 0xFF
	mon.spDefenseEV = (ss2[1] >> 8) & 0xFF
	mon.cool = (ss2[1] >> 16) & 0xFF
	mon.beauty = ss2[1] >> 24
	mon.cute = ss2[2] & 0xFF
	mon.smart = (ss2[2] >> 8) & 0xFF
	mon.tough = (ss2[2] >> 16) & 0xFF
	mon.hiddenNature = ss2[2] >> 24

	mon.pokerus = ss3[0] & 0xFF
	mon.metLocation = (ss3[0] >> 8) & 0xFF
	flags = ss3[0] >> 16
	mon.metLevel = flags & 0x7F
	mon.metGame = (flags >> 7) & 0xF
	mon.pokeball = (flags >> 11) & 0xF
	mon.otGender = (flags >> 15) & 0x1
	flags = ss3[1]
	mon.hpIV = (flags >> 0) & 0x1F
	mon.attackIV = (flags >> 5) & 0x1F
	mon.defenseIV = (flags >> 10) & 0x1F
	mon.speedIV = (flags >> 15) & 0x1F
	mon.spAttackIV = (flags >> 20) & 0x1F
	mon.spDefenseIV = (flags >> 25) & 0x1F
	-- Bit 30 is another "isEgg" bit
	flags = ss3[2]
	mon.coolRibbon = flags & 7
	mon.beautyRibbon = (flags >> 3) & 7
	mon.cuteRibbon = (flags >> 6) & 7
	mon.smartRibbon = (flags >> 9) & 7
	mon.toughRibbon = (flags >> 12) & 7
	mon.championRibbon = (flags >> 15) & 1
	mon.winningRibbon = (flags >> 16) & 1
	mon.victoryRibbon = (flags >> 17) & 1
	mon.artistRibbon = (flags >> 18) & 1
	mon.effortRibbon = (flags >> 19) & 1
	mon.marineRibbon = (flags >> 20) & 1
	mon.landRibbon = (flags >> 21) & 1
	mon.skyRibbon = (flags >> 22) & 1
	mon.countryRibbon = (flags >> 23) & 1
	mon.nationalRibbon = (flags >> 24) & 1
	mon.earthRibbon = (flags >> 25) & 1
	mon.worldRibbon = (flags >> 26) & 1
	mon.altAbility = (flags >> 29) & 3
	return mon
end

function readPartyMon(address)
	local mon = readBoxMon(address)
	mon.status = emu:read32(address + 80)
	mon.level = emu:read8(address + 84)
	-- if (levelCap == 0) then
	-- 	levelCap = mon.level
	-- end
	mon.mail = emu:read8(address + 85)
	mon.hp = emu:read16(address + 86)
	mon.maxHP = emu:read16(address + 88)
	mon.attack = emu:read16(address + 90)
	mon.defense = emu:read16(address + 92)
	mon.speed = emu:read16(address + 94)
	mon.spAttack = emu:read16(address + 96)
	mon.spDefense = emu:read16(address + 98)
	return mon
end

function getAbility(mon)
	current = ability[(mon.species*3)+1+mon.altAbility]
    if (current == "None") then
        current = ability[(mon.species*3)+1]
    end
    return current
end

function getNature(mon)
	if (mon.hiddenNature == 0) then
		return nature[(mon.personality % 25)+1]
	end
	return nature[mon.hiddenNature+1]
end

function getHP(mon)
    hptype = ((mon.hpIV%2 + (2*(mon.attackIV%2))+(4*(mon.defenseIV%2))+(8*(mon.speedIV%2))+(16*(mon.spAttackIV%2))+(32*(mon.spDefenseIV%2)))*5)/21
    hptype = math.floor(hptype)
	if (hptype == 0) then
		return "Fighting"
	end
	if (hptype == 1) then
		return "Flying"
	end
	if (hptype == 2) then
		return "Poison"
	end
	if (hptype == 3) then
		return "Ground"
	end
	if (hptype == 4) then
		return "Rock"
	end
	if (hptype ==5) then
		return "Bug"
	end
	if (hptype == 6) then
		return "Ghost"
	end
	if (hptype ==7) then
		return "Steel"
	end
	if (hptype == 8) then
		return "Fire"
	end
	if (hptype == 9) then
		return "Water"
	end
	if (hptype == 10) then
		return "Grass"
	end
	if (hptype == 11) then
		return "Electric"
	end
	if (hptype == 12) then
		return "Psychic"
	end
	if (hptype == 13) then
		return "Ice"
	end
	if (hptype == 14) then
		return "Dragon"
	end
	if (hptype == 15) then
		return "Dark"
	end
end

function getPartyPrint(mon)
	str = ""
	str = str .. mons[mon.species]
	str = str .. string.format("\n")
	str = str .. "Ability: " .. string.format("%s", getAbility(mon)) .. string.format("\n")
	str = str .. string.format("Level: %d\n", mon.level)
	str = str .. string.format("%s", getNature(mon)) .. " Nature" .. string.format("\n")
	str = str .. string.format("IVs: %d HP / %d Atk / %d Def / %d SpA / %d SpD / %d Spe", mon.hpIV, mon.attackIV, mon.defenseIV, mon.spAttackIV, mon.spDefenseIV, mon.speedIV) .. string.format("\n")
	for i=1,4 do
		local mv = move[mon.moves[i] + 1]
		if(mv == "Hidden Power") then
			str = str .. string.format("- Hidden Power %s\n", getHP(mon))
			else
			if(mv ~= "") then
				str = str .. string.format("- %s\n", mv)
			end
		end
	end
	str = str .. string.format("\n")
	return str
end

function getPCPrint(mon)
	str = ""
	str = str ..  mons[mon.species]
	str = str .. string.format("\n")
	str = str .. "Ability: " .. string.format("%s", getAbility(mon)) .. string.format("\n")
	-- str = str .. string.format("Level: %d\n", levelCap)
	str = str .. string.format("Level: %d\n", calcLevel(mon.experience, mon.species))
	str = str .. string.format("%s", getNature(mon)) .. " Nature" .. string.format("\n")
	str = str .. string.format("IVs: %d HP / %d Atk / %d Def / %d SpA / %d SpD / %d Spe", mon.hpIV, mon.attackIV, mon.defenseIV, mon.spAttackIV, mon.spDefenseIV, mon.speedIV) .. string.format("\n")
	for i=1,4 do
		local mv = move[mon.moves[i] + 1]
		if(mv == "Hidden Power") then
			str = str .. string.format("- Hidden Power %s\n", getHP(mon))
			else
			if(mv ~= "") then
				str = str .. string.format("- %s\n", mv)
			end
		end
	end
	str = str .. string.format("\n")
	return str
end

function printPartyStatus(buffer)
    address = emu:read32(storageLoc) + 4
    i = 0
	buffer:clear()
	for _, mon in ipairs(getParty()) do
		if (mon.species ~= 0) then
			buffer:print(getPartyPrint(mon))
		end
	end
    while i<120 do
		if (emu:read32(address) ~=0) then
			buffer:print(getPCPrint(readBoxMon(address)))
		end
		i = i+1
		address = address + 80
	end
end

function getHP(mon)
    hptype = ((mon.hpIV%2 + (2*(mon.attackIV%2))+(4*(mon.defenseIV%2))+(8*(mon.speedIV%2))+(16*(mon.spAttackIV%2))+(32*(mon.spDefenseIV%2)))*5)/21
    hptype = math.floor(hptype)
	if (hptype == 0) then
		return "Fighting"
	end
	if (hptype == 1) then
		return "Flying"
	end
	if (hptype == 2) then
		return "Poison"
	end
	if (hptype == 3) then
		return "Ground"
	end
	if (hptype == 4) then
		return "Rock"
	end
	if (hptype ==5) then
		return "Bug"
	end
	if (hptype == 6) then
		return "Ghost"
	end
	if (hptype ==7) then
		return "Steel"
	end
	if (hptype == 8) then
		return "Fire"
	end
	if (hptype == 9) then
		return "Water"
	end
	if (hptype == 10) then
		return "Grass"
	end
	if (hptype == 11) then
		return "Electric"
	end
	if (hptype == 12) then
		return "Psychic"
	end
	if (hptype == 13) then
		return "Ice"
	end
	if (hptype == 14) then
		return "Dragon"
	end
	if (hptype == 15) then
		return "Dark"
	end
end

function getHiddens(buffer)
	address = emu:read32(storageLoc) + 4
	i = 0
	buffer:clear()
	for _, mon in ipairs(getParty()) do
		if (mon.species ~= 0) then
			buffer:print(string.format("%s - %s\n", mons[mon.species], getHP(mon)))
		end
	end
	while i<120 do
		if (emu:read32(address) ~=0) then 
			buffer:print(string.format("%s - %s\n",mons[readBoxMon(address).species], getHP(readBoxMon(address))))
		end
		i = i+1
		address = address + 80
	end
end

function hiddens()
	if not hiddenBuffer then
		console:log("error")
		return
	end
	getHiddens(hiddenBuffer)
end

function startScript()
	console:log('To update your exports type "export()"')
	if not partyBuffer then
		partyBuffer = console:createBuffer("Showdown Export")
		partyBuffer:setSize(200,1000)
		export()
	end
	if not hiddenBuffer then
		hiddenBuffer = console:createBuffer("Hidden Powers")
		hiddenBuffer:setSize(200,200)
		hiddens()
	end
end

function export()
	if not partyBuffer then
		console:log("error")
		return
	end
	printPartyStatus(partyBuffer)
	levelCap = 0
end

callbacks:add("start", startScript)
if emu then
	startScript()
end
