# 1 "data/maps/MtPyre_6F/scripts.pory"

# 2 "data/maps/MtPyre_6F/scripts.pory"
MtPyre_6F_MapScripts::
# 3 "data/maps/MtPyre_6F/scripts.pory"
	.byte 0
# 4 "data/maps/MtPyre_6F/scripts.pory"

# 5 "data/maps/MtPyre_6F/scripts.pory"
MtPyre_6F_EventScript_Valerie::
# 6 "data/maps/MtPyre_6F/scripts.pory"
	trainerbattle_single TRAINER_VALERIE_1, MtPyre_6F_Text_ValerieIntro, MtPyre_6F_Text_ValerieDefeat
# 7 "data/maps/MtPyre_6F/scripts.pory"
	msgbox MtPyre_6F_Text_ValeriePostBattle, MSGBOX_AUTOCLOSE
# 8 "data/maps/MtPyre_6F/scripts.pory"
	release
# 9 "data/maps/MtPyre_6F/scripts.pory"
	end
# 10 "data/maps/MtPyre_6F/scripts.pory"

# 11 "data/maps/MtPyre_6F/scripts.pory"
MtPyre_6F_EventScript_RegisterValerie::
# 12 "data/maps/MtPyre_6F/scripts.pory"
	special PlayerFaceTrainerAfterBattle
# 13 "data/maps/MtPyre_6F/scripts.pory"
	waitmovement 0
# 14 "data/maps/MtPyre_6F/scripts.pory"
	msgbox MtPyre_6F_Text_ValerieRegister, MSGBOX_DEFAULT
# 15 "data/maps/MtPyre_6F/scripts.pory"
	register_matchcall TRAINER_VALERIE_1
# 16 "data/maps/MtPyre_6F/scripts.pory"
	release
# 17 "data/maps/MtPyre_6F/scripts.pory"
	end
# 18 "data/maps/MtPyre_6F/scripts.pory"

# 19 "data/maps/MtPyre_6F/scripts.pory"
MtPyre_6F_EventScript_RematchValerie::
# 20 "data/maps/MtPyre_6F/scripts.pory"
	trainerbattle_rematch TRAINER_VALERIE_1, MtPyre_6F_Text_ValerieRematchIntro, MtPyre_6F_Text_ValerieRematchDefeat
# 21 "data/maps/MtPyre_6F/scripts.pory"
	msgbox MtPyre_6F_Text_ValeriePostRematch, MSGBOX_AUTOCLOSE
# 22 "data/maps/MtPyre_6F/scripts.pory"
	end
# 23 "data/maps/MtPyre_6F/scripts.pory"

# 24 "data/maps/MtPyre_6F/scripts.pory"
MtPyre_6F_EventScript_Cedric::
# 25 "data/maps/MtPyre_6F/scripts.pory"
	trainerbattle_single TRAINER_CEDRIC, MtPyre_6F_Text_CedricIntro, MtPyre_6F_Text_CedricDefeat
# 26 "data/maps/MtPyre_6F/scripts.pory"
	msgbox MtPyre_6F_Text_CedricPostBattle, MSGBOX_AUTOCLOSE
# 27 "data/maps/MtPyre_6F/scripts.pory"
	end
# 28 "data/maps/MtPyre_6F/scripts.pory"

# 29 "data/maps/MtPyre_6F/scripts.pory"
MtPyre_6F_Text_ValerieIntro:
# 30 "data/maps/MtPyre_6F/scripts.pory"
	.string "When I'm here…\n"
# 31 "data/maps/MtPyre_6F/scripts.pory"
	.string "A curious power flows into me…$"
# 32 "data/maps/MtPyre_6F/scripts.pory"

# 33 "data/maps/MtPyre_6F/scripts.pory"
MtPyre_6F_Text_ValerieDefeat:
# 34 "data/maps/MtPyre_6F/scripts.pory"
	.string "The power is ebbing away…$"
# 35 "data/maps/MtPyre_6F/scripts.pory"

# 36 "data/maps/MtPyre_6F/scripts.pory"
MtPyre_6F_Text_ValeriePostBattle:
# 37 "data/maps/MtPyre_6F/scripts.pory"
	.string "Perhaps the power is from the spirits\n"
# 38 "data/maps/MtPyre_6F/scripts.pory"
	.string "of Pokémon in fitful sleep here…$"
# 39 "data/maps/MtPyre_6F/scripts.pory"

# 40 "data/maps/MtPyre_6F/scripts.pory"
MtPyre_6F_Text_ValerieRegister:
# 41 "data/maps/MtPyre_6F/scripts.pory"
	.string "Fufufu… I lost the match, but…\n"
# 42 "data/maps/MtPyre_6F/scripts.pory"
	.string "I have this little ability…\p"
# 43 "data/maps/MtPyre_6F/scripts.pory"
	.string "Without ever laying my hands on\n"
# 44 "data/maps/MtPyre_6F/scripts.pory"
	.string "your Pokénav… Hiyah!$"
# 45 "data/maps/MtPyre_6F/scripts.pory"

# 46 "data/maps/MtPyre_6F/scripts.pory"
MtPyre_6F_Text_ValerieRematchIntro:
# 47 "data/maps/MtPyre_6F/scripts.pory"
	.string "Behind you…\n"
# 48 "data/maps/MtPyre_6F/scripts.pory"
	.string "What is it…$"
# 49 "data/maps/MtPyre_6F/scripts.pory"

# 50 "data/maps/MtPyre_6F/scripts.pory"
MtPyre_6F_Text_ValerieRematchDefeat:
# 51 "data/maps/MtPyre_6F/scripts.pory"
	.string "Something faded away…$"
# 52 "data/maps/MtPyre_6F/scripts.pory"

# 53 "data/maps/MtPyre_6F/scripts.pory"
MtPyre_6F_Text_ValeriePostRematch:
# 54 "data/maps/MtPyre_6F/scripts.pory"
	.string "The Pokémon at rest here…\n"
# 55 "data/maps/MtPyre_6F/scripts.pory"
	.string "Sometimes, they play…$"
# 56 "data/maps/MtPyre_6F/scripts.pory"

# 57 "data/maps/MtPyre_6F/scripts.pory"
MtPyre_6F_Text_CedricIntro:
# 58 "data/maps/MtPyre_6F/scripts.pory"
	.string "Have you lost your bearings?\n"
# 59 "data/maps/MtPyre_6F/scripts.pory"
	.string "Have no fear for I am here!$"
# 60 "data/maps/MtPyre_6F/scripts.pory"

# 61 "data/maps/MtPyre_6F/scripts.pory"
MtPyre_6F_Text_CedricDefeat:
# 62 "data/maps/MtPyre_6F/scripts.pory"
	.string "Weren't you lost?$"
# 63 "data/maps/MtPyre_6F/scripts.pory"

# 64 "data/maps/MtPyre_6F/scripts.pory"
MtPyre_6F_Text_CedricPostBattle:
# 65 "data/maps/MtPyre_6F/scripts.pory"
	.string "I had this feeling that a lost Trainer\n"
# 66 "data/maps/MtPyre_6F/scripts.pory"
	.string "would be panicked and easy to beat.\p"
# 67 "data/maps/MtPyre_6F/scripts.pory"
	.string "It's dirty and I won't try it again…$"
